/* Copy the browser sql.js WASM into /public under a content-hashed name and
   generate the matching TypeScript URL. This makes a one-year immutable CDN
   policy safe while Node tests continue using sql.js's native loader. */
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'node_modules', 'sql.js', 'dist');
const pub = join(root, 'public');
const source = join(dist, 'sql-wasm-browser.wasm');
const hash = createHash('sha256').update(readFileSync(source)).digest('hex').slice(0, 12);
const publicName = `sql-wasm-browser.${hash}.wasm`;

mkdirSync(pub, { recursive: true });
copyFileSync(source, join(pub, publicName));
writeFileSync(
  join(root, 'lib', 'sqlWasmAsset.generated.ts'),
  `/* Generated by scripts/copyWasm.mjs. Do not edit by hand. */\nexport const SQL_WASM_URL = '/${publicName}';\n`
);
console.log(`copied sql.js WASM -> public/${publicName}`);
