/* Query battery for scripts/fuzzTrace.ts: generic queries derived from each
   schema's metadata, hand-written adversarial and dialect queries per schema,
   and mutation sequences. */
import type { TableData } from '../lib/db';
import type { TableMeta } from '../lib/schemas';

export interface FuzzQuery {
  sql: string;
  /** ok: must succeed. refused: both SQLite and the app must reject. either: documented as unsupported; rejection is fine. */
  expect?: 'ok' | 'refused' | 'either';
  /** Skip SQLite's own run (statements that would hang or take too long there). */
  skipOracle?: boolean;
  /** The app accepts this on purpose although raw SQLite would not (a keyword alias, a schema prefix). */
  lenient?: boolean;
}

const q = (sql: string, expect: FuzzQuery['expect'] = 'ok'): FuzzQuery => ({ sql, expect });
const refused = (sql: string): FuzzQuery => ({ sql, expect: 'refused' });
const either = (sql: string): FuzzQuery => ({ sql, expect: 'either' });

const KEYWORDS = new Set(['order', 'group', 'select', 'from', 'where', 'table', 'index', 'values', 'set', 'key', 'default', 'check']);
export function ident(name: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name) && !KEYWORDS.has(name.toLowerCase()) ? name : `"${name.replace(/"/g, '""')}"`;
}
const isNumeric = (type?: string) => /int|dec|num|real|float|double|money|bit|serial/i.test(type ?? '');
const lit = (v: unknown): string =>
  v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;

/* --- generic, metadata-driven ------------------------------------------ */

export function genericQueries(schema: TableMeta[], data: Record<string, TableData>): FuzzQuery[] {
  const out: FuzzQuery[] = [];
  for (const table of schema) {
    const T = ident(table.name);
    const rows = data[table.name]?.rows ?? [];
    const cols = table.columns;
    const col = (i: number) => ident(cols[i].name);
    const nums = cols.map((c, i) => [c, i] as const).filter(([c]) => isNumeric(c.type) && !c.pk);
    const texts = cols.map((c, i) => [c, i] as const).filter(([c]) => !isNumeric(c.type) && !c.pk);
    const first = cols[0] ? col(0) : '*';
    const second = cols[1] ? col(1) : first;
    const valueAt = (i: number) => rows.map((r) => r[i]).find((v) => v !== null && v !== undefined);
    const numAt = (i: number) => {
      const vals = rows.map((r) => r[i]).filter((v): v is number => typeof v === 'number').sort((a, b) => a - b);
      return vals[Math.floor(vals.length / 2)] ?? 0;
    };

    out.push(q(`SELECT * FROM ${T}`));
    out.push(q(`SELECT ${first}, ${second} FROM ${T} ORDER BY ${second} DESC, ${first}`));
    out.push(q(`SELECT COUNT(*) AS n FROM ${T}`));
    out.push(q(`SELECT * FROM ${T} LIMIT 3`));
    out.push(q(`SELECT * FROM ${T} LIMIT 3 OFFSET 2`));
    out.push(q(`SELECT * FROM ${T} ORDER BY 1 DESC LIMIT 2, 3`));
    out.push(q(`SELECT ${first} FROM ${T} t WHERE t.${first} IS NOT NULL`));
    out.push(q(`SELECT * FROM ${T} WHERE 1 = 0`));
    if (nums.length) {
      const [c, i] = nums[0];
      const n = numAt(i);
      out.push(q(`SELECT ${first}, ${ident(c.name)} FROM ${T} WHERE ${ident(c.name)} > ${n}`));
      out.push(q(`SELECT ${first} FROM ${T} WHERE ${ident(c.name)} BETWEEN ${n - 1} AND ${n + 1}`));
      out.push(q(`SELECT ${first}, ${ident(c.name)} * 2 AS doubled, ${ident(c.name)} / 0 AS div0 FROM ${T}`));
      out.push(q(`SELECT SUM(${ident(c.name)}) AS total, AVG(${ident(c.name)}) AS mean, MIN(${ident(c.name)}), MAX(${ident(c.name)}) FROM ${T}`));
      out.push(q(`SELECT ${first}, CASE WHEN ${ident(c.name)} > ${n} THEN 'high' WHEN ${ident(c.name)} IS NULL THEN 'none' ELSE 'low' END AS band FROM ${T} ORDER BY band, 1`));
      out.push(q(`SELECT * FROM ${T} WHERE NOT (${ident(c.name)} <= ${n}) OR ${ident(c.name)} IS NULL`));
      out.push(q(`SELECT ${first} FROM ${T} ORDER BY ${ident(c.name)} DESC NULLS LAST LIMIT 4`));
    }
    if (texts.length) {
      const [c, i] = texts[0];
      const v = valueAt(i);
      const C = ident(c.name);
      out.push(q(`SELECT DISTINCT ${C} FROM ${T} ORDER BY ${C}`));
      out.push(q(`SELECT ${first} FROM ${T} WHERE ${C} = ${lit(v)}`));
      out.push(q(`SELECT ${first} FROM ${T} WHERE ${C} LIKE ${lit(String(v ?? '').slice(0, 1) + '%')}`));
      out.push(q(`SELECT ${first} FROM ${T} WHERE ${C} IN (${lit(v)}, 'nothing-like-this', ${lit(v)})`));
      out.push(q(`SELECT ${first} FROM ${T} WHERE ${C} IS NULL OR ${C} = ''`));
      out.push(q(`SELECT UPPER(${C}) AS up, LENGTH(${C}) AS len FROM ${T} ORDER BY len DESC, up`));
      out.push(q(`SELECT ${C}, COUNT(*) AS n FROM ${T} GROUP BY ${C} ORDER BY n DESC, ${C}`));
      out.push(q(`SELECT ${C}, COUNT(*) FROM ${T} GROUP BY ${C} HAVING COUNT(*) > 1`));
      out.push(q(`SELECT ${C}, COUNT(*) FROM ${T} GROUP BY 1 ORDER BY 2 DESC, 1 LIMIT 3`));
      out.push(q(`SELECT ${C} AS k, COUNT(*) AS n FROM ${T} GROUP BY k HAVING n >= 1 ORDER BY n DESC, k`));
      out.push(q(`SELECT DISTINCT UPPER(${C}) AS u FROM ${T} ORDER BY u DESC`));
      out.push(q(`SELECT ${C} AS label FROM ${T} WHERE ${C} IS NOT NULL ORDER BY label LIMIT 5`));
      if (nums.length) {
        const N = ident(nums[0][0].name);
        out.push(q(`SELECT ${C}, SUM(${N}) AS total, AVG(${N}) AS mean FROM ${T} GROUP BY ${C} HAVING SUM(${N}) > 0 ORDER BY total DESC`));
        out.push(q(`SELECT ${C}, ${N}, ROW_NUMBER() OVER (PARTITION BY ${C} ORDER BY ${N} DESC) AS rn FROM ${T} ORDER BY ${C}, rn`));
        out.push(q(`SELECT ${first}, ${N}, SUM(${N}) OVER (ORDER BY ${first}) AS running FROM ${T} ORDER BY ${first}`));
        out.push(q(`SELECT ${first} FROM ${T} WHERE ${N} > (SELECT AVG(${N}) FROM ${T})`));
        out.push(q(`SELECT ${C}, MAX(${N}) FROM ${T} GROUP BY ${C} HAVING MAX(${N}) >= (SELECT AVG(${N}) FROM ${T}) ORDER BY 1`));
      }
    }
    // self join on any table
    out.push(q(`SELECT a.${first}, b.${first} FROM ${T} a JOIN ${T} b ON a.${first} < b.${first} ORDER BY 1, 2 LIMIT 10`));
    out.push(q(`SELECT COUNT(*) FROM ${T} a, ${T} b`));
    out.push(q(`SELECT * FROM (SELECT ${first}, ${second} FROM ${T}) AS d WHERE d.${first} IS NOT NULL`));
    out.push(q(`WITH t AS (SELECT * FROM ${T}) SELECT COUNT(*) FROM t`));
    out.push(q(`SELECT ${first} FROM ${T} UNION ALL SELECT ${first} FROM ${T}`));
    out.push(q(`SELECT ${first} FROM ${T} EXCEPT SELECT ${first} FROM ${T} WHERE 1 = 0`));

    for (const c of cols) {
      if (!c.fk) continue;
      const P = ident(c.fk.table);
      const PC = ident(c.fk.column);
      const FK = ident(c.name);
      const parent = schema.find((t) => t.name === c.fk!.table);
      const parentText = parent?.columns.find((pc) => !isNumeric(pc.type) && !pc.pk) ?? parent?.columns[1] ?? parent?.columns[0];
      const PT = ident(parentText?.name ?? c.fk.column);
      const self = c.fk.table === table.name;
      const ca = self ? 'c' : ident(table.name);
      const pa = self ? 'p' : P;
      const fromSelf = self ? `${T} c JOIN ${T} p` : `${T} JOIN ${P}`;
      out.push(q(`SELECT ${ca}.${first}, ${pa}.${PT} FROM ${fromSelf} ON ${ca}.${FK} = ${pa}.${PC}`));
      out.push(q(`SELECT ${ca}.${first}, ${pa}.${PT} FROM ${self ? `${T} c LEFT JOIN ${T} p` : `${T} LEFT JOIN ${P}`} ON ${ca}.${FK} = ${pa}.${PC} ORDER BY 1`));
      out.push(q(`SELECT ${pa}.${PT}, ${ca}.${first} FROM ${self ? `${T} p LEFT JOIN ${T} c` : `${P} LEFT JOIN ${T}`} ON ${ca}.${FK} = ${pa}.${PC}`));
      out.push(q(`SELECT ${pa}.${PT}, ${ca}.${first} FROM ${self ? `${T} c RIGHT JOIN ${T} p` : `${T} RIGHT JOIN ${P}`} ON ${ca}.${FK} = ${pa}.${PC}`));
      out.push(q(`SELECT ${pa}.${PT}, ${ca}.${first} FROM ${self ? `${T} c FULL OUTER JOIN ${T} p` : `${T} FULL OUTER JOIN ${P}`} ON ${ca}.${FK} = ${pa}.${PC}`));
      out.push(q(`SELECT ${ca}.${first}, ${pa}.${PT} FROM ${self ? `${T} c, ${T} p` : `${T}, ${P}`} WHERE ${ca}.${FK} = ${pa}.${PC}`));
      out.push(q(`SELECT ${pa}.${PT}, COUNT(${ca}.${first}) AS n FROM ${self ? `${T} p LEFT JOIN ${T} c` : `${P} LEFT JOIN ${T}`} ON ${ca}.${FK} = ${pa}.${PC} GROUP BY ${pa}.${PC}, ${pa}.${PT} ORDER BY n DESC, 1`));
      out.push(q(`SELECT ${pa}.${PT} FROM ${self ? `${T} p` : P} WHERE NOT EXISTS (SELECT 1 FROM ${T} x WHERE x.${FK} = ${pa}.${PC})`));
      out.push(q(`SELECT ${PT} FROM ${P} WHERE ${PC} IN (SELECT ${FK} FROM ${T})`));
      out.push(q(`SELECT ${PT} FROM ${P} WHERE ${PC} NOT IN (SELECT ${FK} FROM ${T} WHERE ${FK} IS NOT NULL)`));
      out.push(q(`SELECT ${PT}, (SELECT COUNT(*) FROM ${T} x WHERE x.${FK} = ${self ? 'p' : P}.${PC}) AS n FROM ${self ? `${T} p` : P}`));
      out.push(q(`SELECT ${pa}.${PT}, d.n FROM ${self ? `${T} p` : P} JOIN (SELECT ${FK} AS k, COUNT(*) AS n FROM ${T} GROUP BY ${FK}) d ON d.k = ${pa}.${PC}`));
      out.push(q(`WITH counts AS (SELECT ${FK} AS k, COUNT(*) AS n FROM ${T} GROUP BY ${FK}) SELECT ${PT}, n FROM ${P} JOIN counts ON counts.k = ${P}.${PC} ORDER BY n DESC`));
      out.push(q(`SELECT ${PC} FROM ${P} INTERSECT SELECT ${FK} FROM ${T}`));
      if (!self && c.name.toLowerCase() === c.fk.column.toLowerCase()) {
        out.push(q(`SELECT ${T}.${first}, ${P}.${PT} FROM ${T} JOIN ${P} USING (${FK})`));
        out.push(q(`SELECT ${T}.${first}, ${P}.${PT} FROM ${T} LEFT JOIN ${P} USING (${FK}) ORDER BY 1`));
      }
      out.push(q(`SELECT ${PC} FROM ${P} EXCEPT SELECT ${FK} FROM ${T}`));
      out.push(q(`SELECT ${pa}.${PT}, ${ca}.${first} FROM ${self ? `${T} c LEFT JOIN ${T} p` : `${T} LEFT JOIN ${P}`} ON ${ca}.${FK} = ${pa}.${PC} WHERE ${pa}.${PC} IS NULL`));
    }
  }
  return out;
}

/* --- hand-written per schema ------------------------------------------ */

const HAND: Record<string, FuzzQuery[]> = {
  observatory: [
    q('SELECT GIVEN_NAME, FAMILY_NAME FROM ASTRONOMER WHERE HOME_CITY = \'Tucson\' ORDER BY FAMILY_NAME'),
    q("SELECT A.GIVEN_NAME || ' ' || A.FAMILY_NAME AS observer, T.TELESCOPE_NAME, G.TARGET_NAME, O.OBSERVED_ON FROM OBSERVATION O JOIN ASTRONOMER A ON A.ASTRONOMER_ID = O.ASTRONOMER_ID JOIN TELESCOPE T ON T.TELESCOPE_ID = O.TELESCOPE_ID JOIN TARGET G ON G.TARGET_ID = O.TARGET_ID ORDER BY O.OBSERVED_ON"),
    q('SELECT T.TELESCOPE_NAME, COUNT(O.OBSERVATION_ID) AS sessions, SUM(O.EXPOSURE_MIN) AS minutes FROM TELESCOPE T LEFT JOIN OBSERVATION O ON O.TELESCOPE_ID = T.TELESCOPE_ID GROUP BY T.TELESCOPE_ID ORDER BY minutes DESC'),
    q("SELECT TARGET_TYPE, COUNT(*) FROM TARGET GROUP BY TARGET_TYPE HAVING COUNT(*) >= 2 ORDER BY 2 DESC, 1"),
    q('SELECT G.CONSTELLATION, AVG(O.EXPOSURE_MIN) AS avg_exp FROM TARGET G JOIN OBSERVATION O ON O.TARGET_ID = G.TARGET_ID GROUP BY G.CONSTELLATION HAVING AVG(O.EXPOSURE_MIN) > 30 ORDER BY avg_exp DESC'),
    q("SELECT * FROM OBSERVATION WHERE OBSERVED_ON BETWEEN '2026-04-01' AND '2026-04-30' ORDER BY OBSERVED_ON"),
    q("SELECT OBSERVATION_ID, YEAR(OBSERVED_ON) AS y, MONTH(OBSERVED_ON) AS m FROM OBSERVATION"),
    q("SELECT OBSERVATION_ID, EXTRACT(MONTH FROM OBSERVED_ON) AS m FROM OBSERVATION WHERE EXTRACT(YEAR FROM OBSERVED_ON) = 2026"),
    q("SELECT OBSERVATION_ID, DATE_FORMAT(OBSERVED_ON, '%Y/%m') AS ym FROM OBSERVATION ORDER BY 1"),
    q("SELECT DATEDIFF('2026-06-01', OBSERVED_ON) AS days_ago, OBSERVATION_ID FROM OBSERVATION ORDER BY days_ago"),
    q("SELECT OBSERVATION_ID, DATE_ADD(OBSERVED_ON, INTERVAL 7 DAY) AS week_later FROM OBSERVATION"),
    q("SELECT OBSERVATION_ID, OBSERVED_ON + INTERVAL '1 month' AS later FROM OBSERVATION"),
    q("SELECT strftime('%m', OBSERVED_ON) AS m, COUNT(*) FROM OBSERVATION GROUP BY m"),
    q("SELECT OBSERVATION_ID FROM OBSERVATION WHERE OBSERVED_ON > DATE '2026-04-01'"),
    q("SELECT TELESCOPE_NAME, APERTURE_CM, RANK() OVER (ORDER BY APERTURE_CM DESC) AS rk, DENSE_RANK() OVER (ORDER BY LOCATION) AS dr FROM TELESCOPE"),
    q('SELECT OBSERVATION_ID, EXPOSURE_MIN, LAG(EXPOSURE_MIN) OVER (ORDER BY OBSERVED_ON) AS prev, LEAD(EXPOSURE_MIN, 1, 0) OVER (ORDER BY OBSERVED_ON) AS next FROM OBSERVATION'),
    q('SELECT ASTRONOMER_ID, EXPOSURE_MIN, AVG(EXPOSURE_MIN) OVER (PARTITION BY ASTRONOMER_ID) AS per_person FROM OBSERVATION ORDER BY ASTRONOMER_ID, OBSERVATION_ID'),
    either('SELECT OBSERVATION_ID, SUM(EXPOSURE_MIN) OVER (ORDER BY OBSERVED_ON ROWS BETWEEN 1 PRECEDING AND CURRENT ROW) FROM OBSERVATION'),
    q('SELECT * FROM (SELECT ASTRONOMER_ID, COUNT(*) AS n FROM OBSERVATION GROUP BY ASTRONOMER_ID) x WHERE x.n > 1'),
    q('SELECT A.FAMILY_NAME FROM ASTRONOMER A WHERE EXISTS (SELECT 1 FROM OBSERVATION O WHERE O.ASTRONOMER_ID = A.ASTRONOMER_ID AND O.EXPOSURE_MIN > 50)'),
    q('SELECT A.FAMILY_NAME, (SELECT MAX(EXPOSURE_MIN) FROM OBSERVATION O WHERE O.ASTRONOMER_ID = A.ASTRONOMER_ID) AS longest FROM ASTRONOMER A ORDER BY longest DESC'),
    q("SELECT O1.OBSERVATION_ID, O2.OBSERVATION_ID FROM OBSERVATION O1 JOIN OBSERVATION O2 ON O1.TARGET_ID = O2.TARGET_ID AND O1.OBSERVATION_ID < O2.OBSERVATION_ID"),
    q('SELECT T.TELESCOPE_NAME FROM TELESCOPE T WHERE T.APERTURE_CM > ALL (SELECT APERTURE_CM FROM TELESCOPE WHERE LOCATION = \'Red Basin\')', 'either'),
    q("SELECT HOME_CITY, GROUP_CONCAT(FAMILY_NAME, ', ') AS people FROM ASTRONOMER GROUP BY HOME_CITY"),
    q("SELECT HOME_CITY, GROUP_CONCAT(FAMILY_NAME SEPARATOR '; ') AS people FROM ASTRONOMER GROUP BY HOME_CITY"),
    q("SELECT HOME_CITY, LISTAGG(FAMILY_NAME, ', ') WITHIN GROUP (ORDER BY FAMILY_NAME) AS people FROM ASTRONOMER GROUP BY HOME_CITY"),
    q('SELECT ASTRONOMER_ID FROM ASTRONOMER MINUS SELECT ASTRONOMER_ID FROM OBSERVATION'),
    q("SELECT SYSDATE FROM DUAL", 'either'),
    q("SELECT 1 + 1 AS two FROM DUAL"),
    q('SELECT * FROM OBSERVATION WHERE ROWNUM <= 3'),
    q('SELECT TOP 3 * FROM OBSERVATION ORDER BY EXPOSURE_MIN DESC'),
    q('SELECT * FROM OBSERVATION ORDER BY EXPOSURE_MIN DESC FETCH FIRST 3 ROWS ONLY'),
    q('SELECT * FROM OBSERVATION ORDER BY EXPOSURE_MIN DESC OFFSET 2 ROWS FETCH NEXT 3 ROWS ONLY'),
    q("SELECT [OBSERVATION_ID], [EXPOSURE_MIN] FROM [OBSERVATION] WHERE [EXPOSURE_MIN] > 40"),
    q("SELECT `OBSERVATION_ID` FROM `OBSERVATION` WHERE `EXPOSURE_MIN` > 40"),
    q('SELECT "OBSERVATION_ID" FROM "OBSERVATION" WHERE "EXPOSURE_MIN" > 40'),
    q("SELECT NVL(NULL, 'none') AS a, COALESCE(NULL, NULL, 3) AS b, IFNULL(NULL, 'x') AS c, NULLIF(1, 1) AS d FROM ASTRONOMER WHERE ASTRONOMER_ID = 1"),
    q("SELECT CAST(EXPOSURE_MIN AS CHAR) AS s, CAST(EXPOSURE_MIN AS UNSIGNED) AS u, CONVERT(INT, EXPOSURE_MIN) AS i, EXPOSURE_MIN::text AS t FROM OBSERVATION LIMIT 3"),
    q("SELECT LEFT(TARGET_NAME, 3) AS l, RIGHT(TARGET_NAME, 3) AS r, LEN(TARGET_NAME) AS n, SUBSTRING(TARGET_NAME FROM 2 FOR 3) AS s, POSITION('a' IN TARGET_NAME) AS p, LOCATE('e', TARGET_NAME) AS l2, LPAD(TARGET_ID, 6, '0') AS pad, TRIM(BOTH ' ' FROM TARGET_NAME) AS tr FROM TARGET"),
    q("SELECT TARGET_NAME FROM TARGET WHERE TARGET_NAME ILIKE '%nebula%'"),
    q("SELECT TARGET_NAME FROM TARGET WHERE TARGET_NAME RLIKE '^[AB]'"),
    q("SELECT TARGET_NAME FROM TARGET WHERE TARGET_NAME REGEXP 'Galaxy$'"),
    q("SELECT TARGET_NAME FROM TARGET WHERE TARGET_NAME GLOB '*Nebula'"),
    q("SELECT EXPOSURE_MIN DIV 10 AS tens, EXPOSURE_MIN MOD 10 AS ones, MOD(EXPOSURE_MIN, 7) AS m7, EXPOSURE_MIN % 7 AS m7b FROM OBSERVATION"),
    q("SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN <=> 42"),
    q("SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN IS DISTINCT FROM 42"),
    q("SELECT * FROM OBSERVATION WHERE OBSERVED_ON = N'2026-03-12'"),
    q("SELECT * FROM OBSERVATION -- trailing comment\nWHERE EXPOSURE_MIN > 40 /* block */ ORDER BY 1"),
    q("SELECT * FROM OBSERVATION # mysql comment\nWHERE EXPOSURE_MIN > 40"),
    q("  \n\t SELECT   *   FROM\n\nOBSERVATION\n\n;\n\n"),
    q('select observation_id from observation where exposure_min > 40 order by observation_id'),
    q('SeLeCt Observation_Id FrOm oBsErVaTiOn'),
    q("SELECT 'O''Brien' AS quoted, 'Ñandú 🦤' AS unicode, '' AS empty"),
    q('SELECT 1'),
    { sql: 'SELECT NULL AS nothing', expect: 'ok', lenient: true },
    q("SELECT 10 / 4 AS int_div, 10.0 / 4 AS real_div, 10 % 4 AS m, -EXPOSURE_MIN AS neg, ABS(-3) AS a, ROUND(2.567, 2) AS r FROM OBSERVATION LIMIT 1"),
    q('SELECT (((((EXPOSURE_MIN))))) FROM OBSERVATION WHERE ((((EXPOSURE_MIN > 40))))'),
    q(`SELECT OBSERVATION_ID FROM OBSERVATION WHERE OBSERVATION_ID IN (${Array.from({ length: 120 }, (_, i) => 5000 + i).join(', ')})`),
    q(`SELECT OBSERVATION_ID FROM OBSERVATION WHERE EXPOSURE_MIN > 0 ${'AND 1 = 1 '.repeat(60)}`),
    q(`SELECT ${'/* pad */ '.repeat(500)} OBSERVATION_ID FROM OBSERVATION`),
    q(`SELECT '${'x'.repeat(5000)}' AS long_text, OBSERVATION_ID FROM OBSERVATION LIMIT 1`),
    q(Array.from({ length: 25 }, (_, i) => `SELECT ${i} AS n`).join(' UNION ALL ')),
    q('SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM OBSERVATION) a) b) c WHERE EXPOSURE_MIN > 50'),
    q('SELECT ASTRONOMER_ID FROM ASTRONOMER WHERE ASTRONOMER_ID IN (SELECT ASTRONOMER_ID FROM OBSERVATION WHERE TARGET_ID IN (SELECT TARGET_ID FROM TARGET WHERE CONSTELLATION IN (SELECT CONSTELLATION FROM TARGET WHERE TARGET_TYPE = \'Nebula\')))'),
    q('SELECT * FROM OBSERVATION O JOIN TELESCOPE T ON T.TELESCOPE_ID = O.TELESCOPE_ID'),
    q('SELECT O.*, T.LOCATION FROM OBSERVATION O JOIN TELESCOPE T ON T.TELESCOPE_ID = O.TELESCOPE_ID WHERE T.APERTURE_CM > 100'),
    either('SELECT * FROM ASTRONOMER JOIN OBSERVATION USING (ASTRONOMER_ID)'),
    q('SELECT ASTRONOMER.FAMILY_NAME, OBSERVATION.OBSERVED_ON FROM ASTRONOMER JOIN OBSERVATION USING (ASTRONOMER_ID)'),
    either('SELECT * FROM ASTRONOMER NATURAL JOIN OBSERVATION'),
    q('SELECT * FROM TELESCOPE CROSS JOIN TARGET'),
    q("SELECT T.TELESCOPE_NAME, G.TARGET_NAME FROM TELESCOPE T JOIN OBSERVATION O ON O.TELESCOPE_ID = T.TELESCOPE_ID OR O.EXPOSURE_MIN > 70 JOIN TARGET G ON G.TARGET_ID = O.TARGET_ID"),
    q('SELECT T.TELESCOPE_NAME, G.TARGET_NAME FROM TELESCOPE T LEFT JOIN OBSERVATION O ON O.TELESCOPE_ID = T.TELESCOPE_ID AND O.EXPOSURE_MIN > 45 LEFT JOIN TARGET G ON G.TARGET_ID = O.TARGET_ID ORDER BY 1, 2'),
    q('SELECT T.TELESCOPE_NAME, G.TARGET_NAME FROM TELESCOPE T LEFT JOIN OBSERVATION O ON O.TELESCOPE_ID = T.TELESCOPE_ID INNER JOIN TARGET G ON G.TARGET_ID = O.TARGET_ID'),
    q('SELECT TELESCOPE.TELESCOPE_NAME FROM TELESCOPE AS T', 'refused'),
    q('SELECT T.TELESCOPE_NAME FROM TELESCOPE t'),
    q('SELECT ASTRONOMER.HOME_CITY FROM ASTRONOMER TELESCOPE', 'refused'),
    q('SELECT OBSERVATION.HOME_CITY FROM OBSERVATION JOIN ASTRONOMER ON ASTRONOMER.ASTRONOMER_ID = OBSERVATION.ASTRONOMER_ID', 'refused'),
    refused('SELECT ASTRONOMER_ID FROM ASTRONOMER JOIN OBSERVATION ON ASTRONOMER.ASTRONOMER_ID = OBSERVATION.ASTRONOMER_ID'),
    refused('SELECT NOPE FROM OBSERVATION'),
    refused('SELECT * FROM NOWHERE'),
    refused('SELECT EXPOSURE_MIN FROM OBSERVATION WHERE SUM(EXPOSURE_MIN) > 10'),
    refused('SELECT SUM(MAX(EXPOSURE_MIN)) FROM OBSERVATION'),
    refused('SELECT * FROM OBSERVATION WHERE'),
    refused('SELEC * FROM OBSERVATION'),
    refused('SELECT * FROM OBSERVATION ORDER BY'),
    refused(''),
    refused('   '),
    refused('-- only a comment'),
    refused('SELECT * FROM OBSERVATION; DROP TABLE OBSERVATION;'),
    refused('SELECT * FROM OBSERVATION; SELECT * FROM TARGET'),
    either('SELECT * FROM sqlite_master'),
    either('PRAGMA table_info(OBSERVATION)'),
    either("ATTACH DATABASE 'x.db' AS x"),
    either("SELECT load_extension('x')"),
    either('DROP TABLE OBSERVATION'),
    either('CREATE TABLE NEW_T (ID INTEGER PRIMARY KEY)'),
    either('ALTER TABLE TARGET ADD COLUMN NOTE TEXT'),
    either('SELECT randomblob(10000000)'),
    { sql: 'WITH RECURSIVE c(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM c WHERE x < 20) SELECT x FROM c', expect: 'either' },
    q("SELECT * FROM OBSERVATION WHERE TELESCOPE_ID = 'ARC' OR 1 = 1"),
    q("SELECT * FROM OBSERVATION WHERE TELESCOPE_ID = '\\' OR 1=1 --'"),
    q('SELECT OBSERVATION_ID FROM OBSERVATION WHERE EXPOSURE_MIN > (SELECT 40)'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION LIMIT (SELECT 2)', 'either'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION LIMIT 0'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION LIMIT -1'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION LIMIT 999999999'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION LIMIT 5 OFFSET 100'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION ORDER BY RANDOM() LIMIT 2'),
    either('SELECT COUNT(*), HOME_CITY FROM ASTRONOMER'),
    q('SELECT HOME_CITY, COUNT(*) FROM ASTRONOMER GROUP BY HOME_CITY, GIVEN_NAME'),
    either('SELECT HOME_CITY, GIVEN_NAME FROM ASTRONOMER GROUP BY HOME_CITY'),
    either('SELECT COUNT(*) FROM ASTRONOMER HAVING COUNT(*) > 3'),
    either('SELECT HOME_CITY AS city FROM ASTRONOMER WHERE city = \'Tucson\''),
    q('SELECT HOME_CITY AS city, COUNT(*) AS n FROM ASTRONOMER GROUP BY city HAVING n > 1 ORDER BY n'),
    q('SELECT GIVEN_NAME FROM ASTRONOMER ORDER BY FAMILY_NAME'),
    q('SELECT DISTINCT HOME_CITY FROM ASTRONOMER ORDER BY HOME_CITY DESC'),
    q('SELECT DISTINCT HOME_CITY FROM ASTRONOMER ORDER BY FAMILY_NAME', 'either'),
    q("SELECT HOME_CITY, CASE HOME_CITY WHEN 'Tucson' THEN 'AZ' WHEN 'Flagstaff' THEN 'AZ' ELSE 'NM' END AS state FROM ASTRONOMER GROUP BY HOME_CITY ORDER BY state, 1"),
    q("SELECT CASE WHEN EXPOSURE_MIN > 40 THEN 'long' ELSE 'short' END AS kind, COUNT(*) FROM OBSERVATION GROUP BY CASE WHEN EXPOSURE_MIN > 40 THEN 'long' ELSE 'short' END"),
    q('SELECT OBSERVATION_ID FROM OBSERVATION ORDER BY CASE WHEN EXPOSURE_MIN > 40 THEN 0 ELSE 1 END, OBSERVATION_ID DESC'),
    q('SELECT COUNT(DISTINCT TELESCOPE_ID) AS scopes, COUNT(TELESCOPE_ID) AS all_rows, TOTAL(EXPOSURE_MIN) AS t FROM OBSERVATION'),
    q("SELECT MAX(TARGET_NAME) AS last_name, MIN(TARGET_NAME) AS first_name FROM TARGET"),
    q('SELECT SUM(EXPOSURE_MIN) FROM OBSERVATION WHERE 1 = 0'),
    q('SELECT AVG(EXPOSURE_MIN) FROM OBSERVATION WHERE EXPOSURE_MIN > 1000'),
    q("SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN = '42'"),
    q("SELECT * FROM OBSERVATION WHERE OBSERVATION_ID = '5001'"),
    q("SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN > '5'"),
    q('SELECT TYPEOF(EXPOSURE_MIN), TYPEOF(OBSERVED_ON), TYPEOF(NULL) FROM OBSERVATION LIMIT 1'),
    either("SELECT * FROM OBSERVATION WHERE OBSERVED_ON LIKE '2026-04%' ESCAPE '\\'"),
    q("SELECT TARGET_NAME FROM TARGET WHERE TARGET_NAME NOT LIKE '%a%' AND TARGET_NAME NOT BETWEEN 'A' AND 'M'"),
    q("SELECT * FROM TARGET WHERE TARGET_ID NOT IN (SELECT TARGET_ID FROM OBSERVATION WHERE EXPOSURE_MIN > 100)"),
    q('SELECT * FROM TARGET WHERE TARGET_ID NOT IN (SELECT NULL)'),
    q("SELECT * FROM TARGET WHERE TARGET_ID IN ()", 'either'),
    q('WITH big AS (SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN > 40), scoped AS (SELECT b.*, T.LOCATION FROM big b JOIN TELESCOPE T ON T.TELESCOPE_ID = b.TELESCOPE_ID) SELECT LOCATION, COUNT(*) FROM scoped GROUP BY LOCATION'),
    q('WITH OBSERVATION AS (SELECT 1 AS OBSERVATION_ID) SELECT * FROM OBSERVATION'),
    q('WITH x(a, b) AS (SELECT OBSERVATION_ID, EXPOSURE_MIN FROM OBSERVATION) SELECT a FROM x WHERE b > 40'),
    q('WITH u AS (SELECT ASTRONOMER_ID AS id FROM ASTRONOMER UNION SELECT TARGET_ID FROM TARGET) SELECT COUNT(*) FROM u'),
    q('SELECT * FROM (SELECT HOME_CITY FROM ASTRONOMER UNION SELECT LOCATION FROM TELESCOPE) places ORDER BY 1'),
    q('SELECT HOME_CITY FROM ASTRONOMER UNION SELECT LOCATION FROM TELESCOPE ORDER BY 1 DESC LIMIT 3'),
    q('SELECT HOME_CITY FROM ASTRONOMER UNION ALL SELECT LOCATION FROM TELESCOPE UNION ALL SELECT CONSTELLATION FROM TARGET'),
    q('SELECT HOME_CITY FROM ASTRONOMER INTERSECT SELECT HOME_CITY FROM ASTRONOMER WHERE ASTRONOMER_ID < 3'),
    refused('SELECT HOME_CITY, GIVEN_NAME FROM ASTRONOMER UNION SELECT LOCATION FROM TELESCOPE'),
    q('SELECT A.GIVEN_NAME FROM ASTRONOMER A WHERE A.ASTRONOMER_ID = (SELECT MAX(ASTRONOMER_ID) FROM ASTRONOMER)'),
    q('SELECT OBSERVATION_ID FROM OBSERVATION O WHERE EXPOSURE_MIN = (SELECT MAX(EXPOSURE_MIN) FROM OBSERVATION I WHERE I.TELESCOPE_ID = O.TELESCOPE_ID)'),
    q('SELECT A.GIVEN_NAME, (SELECT COUNT(*) FROM OBSERVATION O WHERE O.ASTRONOMER_ID = A.ASTRONOMER_ID) AS n, (SELECT MAX(EXPOSURE_MIN) FROM OBSERVATION O WHERE O.ASTRONOMER_ID = A.ASTRONOMER_ID) AS longest FROM ASTRONOMER A'),
    q('SELECT * FROM OBSERVATION a, OBSERVATION b, OBSERVATION c WHERE a.OBSERVATION_ID = b.OBSERVATION_ID AND b.OBSERVATION_ID = c.OBSERVATION_ID'),
    either('SELECT COUNT(*) FROM OBSERVATION a, OBSERVATION b, OBSERVATION c, OBSERVATION d, OBSERVATION e'),
    { sql: 'SELECT COUNT(*) FROM OBSERVATION a, OBSERVATION b, OBSERVATION c, OBSERVATION d, OBSERVATION e, OBSERVATION f', expect: 'either', skipOracle: true },
    q('SELECT OBSERVATION_ID AS "Session Id", EXPOSURE_MIN AS "Minutes (exposure)" FROM OBSERVATION ORDER BY "Minutes (exposure)" DESC'),
    either("SELECT OBSERVATION_ID AS 'Session', EXPOSURE_MIN AS 'Minutes' FROM OBSERVATION ORDER BY 'Minutes'"),
    q('SELECT OBSERVATION_ID AS `Session` FROM OBSERVATION ORDER BY `Session`'),
    q('SELECT OBSERVATION_ID AS [Session] FROM OBSERVATION ORDER BY [Session]'),
    q('SELECT OBSERVATION_ID AS select_ FROM OBSERVATION'),
    q('SELECT OBSERVATION_ID AS "order" FROM OBSERVATION ORDER BY "order"'),
    q('SELECT O.OBSERVATION_ID, O.EXPOSURE_MIN AS O FROM OBSERVATION O ORDER BY O'),
    q("SELECT EXPOSURE_MIN, EXPOSURE_MIN AS EXPOSURE_MIN FROM OBSERVATION"),
    q('SELECT EXPOSURE_MIN * 1.5 AS x, x * 2 AS y FROM OBSERVATION', 'refused'),
    q('SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN > 40 AND (TELESCOPE_ID = \'ARC\' OR TELESCOPE_ID = \'LUX\') AND NOT ASTRONOMER_ID = 3'),
    q("SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN > 40 OR TELESCOPE_ID = 'ARC' AND ASTRONOMER_ID = 5"),
    q("SELECT * FROM OBSERVATION WHERE NOT EXPOSURE_MIN > 40 AND NOT TELESCOPE_ID = 'ARC'"),
    q('SELECT * FROM OBSERVATION WHERE NULL'),
    q('SELECT * FROM OBSERVATION WHERE 1'),
    q("SELECT * FROM OBSERVATION WHERE 'a'"),
    q('SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN'),
    q('SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN = EXPOSURE_MIN'),
    q('SELECT * FROM OBSERVATION WHERE EXPOSURE_MIN = NULL'),
    q('SELECT * FROM OBSERVATION WHERE OBSERVATION_ID IN (5001, 5002) AND OBSERVATION_ID NOT IN (5002)'),
  ],
  transit: [
    q("SELECT ROUTE_NAME, FARE FROM FERRY_ROUTE WHERE TERMINAL_ZONE = 'Central' AND NIGHT_SERVICE = 1 ORDER BY FARE"),
    q('SELECT TERMINAL_ZONE, COUNT(*) AS routes, ROUND(AVG(FARE), 2) AS avg_fare, SUM(SCHEDULED_TRIPS) AS trips FROM FERRY_ROUTE GROUP BY TERMINAL_ZONE HAVING COUNT(*) > 1 ORDER BY avg_fare DESC'),
    q('SELECT ROUTE_NAME, FARE * SCHEDULED_TRIPS AS potential, CROSSING_MIN / 60.0 AS hours FROM FERRY_ROUTE ORDER BY potential DESC LIMIT 5'),
    q('SELECT ROUTE_NAME, FARE, RANK() OVER (PARTITION BY TERMINAL_ZONE ORDER BY FARE DESC) AS rk FROM FERRY_ROUTE ORDER BY TERMINAL_ZONE, rk'),
    q("SELECT ROUTE_NAME FROM FERRY_ROUTE WHERE FARE > (SELECT AVG(FARE) FROM FERRY_ROUTE WHERE NIGHT_SERVICE = 1)"),
    q('SELECT NIGHT_SERVICE, MIN(FARE), MAX(FARE), COUNT(*) FROM FERRY_ROUTE GROUP BY NIGHT_SERVICE'),
    q("SELECT ROUTE_CODE FROM FERRY_ROUTE WHERE ROUTE_CODE LIKE '_0%' ORDER BY ROUTE_CODE"),
    q('SELECT ROUTE_NAME, CASE NIGHT_SERVICE WHEN 1 THEN \'night\' ELSE \'day\' END AS service FROM FERRY_ROUTE ORDER BY service, ROUTE_NAME'),
    q('SELECT a.ROUTE_NAME, b.ROUTE_NAME FROM FERRY_ROUTE a JOIN FERRY_ROUTE b ON a.TERMINAL_ZONE = b.TERMINAL_ZONE AND a.ROUTE_CODE < b.ROUTE_CODE ORDER BY 1, 2'),
    q('SELECT TERMINAL_ZONE FROM FERRY_ROUTE GROUP BY TERMINAL_ZONE HAVING SUM(NIGHT_SERVICE) = 0'),
    q('SELECT SUM(FARE) AS total, SUM(FARE * 1.0) AS total_real, AVG(CROSSING_MIN) FROM FERRY_ROUTE'),
    q('SELECT ROUTE_NAME FROM FERRY_ROUTE WHERE FARE = 8.5'),
    q("SELECT ROUTE_NAME FROM FERRY_ROUTE WHERE FARE = 8.50"),
    q("SELECT ROUTE_NAME FROM FERRY_ROUTE WHERE FARE > '9'"),
    q("SELECT ROUTE_NAME, PRINTF('%.2f', FARE) AS fare_text, FORMAT('%d min', CROSSING_MIN) AS crossing FROM FERRY_ROUTE"),
    q("SELECT ROUTE_NAME, TO_CHAR(FARE, '999.99') AS fare_text FROM FERRY_ROUTE"),
    q('SELECT * FROM FERRY_ROUTE ORDER BY TERMINAL_ZONE, FARE DESC, ROUTE_NAME'),
    q('SELECT * FROM FERRY_ROUTE ORDER BY 3, 4 DESC'),
    q('SELECT ROUTE_NAME FROM FERRY_ROUTE ORDER BY FARE * SCHEDULED_TRIPS'),
    q('SELECT ROUTE_NAME, FARE FROM FERRY_ROUTE WHERE FARE IN (SELECT MAX(FARE) FROM FERRY_ROUTE GROUP BY TERMINAL_ZONE)'),
    q('SELECT z.TERMINAL_ZONE, z.n, f.ROUTE_NAME FROM (SELECT TERMINAL_ZONE, COUNT(*) AS n FROM FERRY_ROUTE GROUP BY TERMINAL_ZONE) z JOIN FERRY_ROUTE f ON f.TERMINAL_ZONE = z.TERMINAL_ZONE WHERE z.n > 1'),
    q('SELECT COUNT(*) FROM FERRY_ROUTE WHERE FARE BETWEEN 5 AND 10 AND CROSSING_MIN NOT BETWEEN 20 AND 40'),
  ],
  festival: [
    q("SELECT A.FAMILY_NAME, S.FILM_TITLE, R.SEATS FROM ATTENDEE A JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID JOIN SCREENING S ON S.SCREENING_ID = R.SCREENING_ID WHERE R.STATUS = 'Confirmed' ORDER BY A.FAMILY_NAME, S.FILM_TITLE"),
    either('SELECT S.FILM_TITLE, V.VENUE_NAME, V.CAPACITY, SUM(R.SEATS) AS booked, V.CAPACITY - COALESCE(SUM(R.SEATS), 0) AS free FROM SCREENING S JOIN VENUE V ON V.VENUE_ID = S.VENUE_ID LEFT JOIN RESERVATION R ON R.SCREENING_ID = S.SCREENING_ID GROUP BY S.SCREENING_ID ORDER BY free'),
    q('SELECT S.FILM_TITLE, V.VENUE_NAME, V.CAPACITY, SUM(R.SEATS) AS booked, V.CAPACITY - COALESCE(SUM(R.SEATS), 0) AS free FROM SCREENING S JOIN VENUE V ON V.VENUE_ID = S.VENUE_ID LEFT JOIN RESERVATION R ON R.SCREENING_ID = S.SCREENING_ID GROUP BY S.SCREENING_ID, V.VENUE_ID ORDER BY free'),
    q("SELECT A.CITY, COUNT(DISTINCT A.ATTENDEE_ID) AS people, COUNT(R.SCREENING_ID) AS reservations FROM ATTENDEE A LEFT JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID GROUP BY A.CITY ORDER BY reservations DESC, A.CITY"),
    q('SELECT A.FAMILY_NAME FROM ATTENDEE A WHERE NOT EXISTS (SELECT 1 FROM RESERVATION R WHERE R.ATTENDEE_ID = A.ATTENDEE_ID)'),
    q("SELECT A.FAMILY_NAME, A.FAVORITE_GENRE FROM ATTENDEE A JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID JOIN SCREENING S ON S.SCREENING_ID = R.SCREENING_ID WHERE S.GENRE = A.FAVORITE_GENRE"),
    q('SELECT A.CITY FROM ATTENDEE A INTERSECT SELECT V.CITY FROM VENUE V'),
    q('SELECT A.CITY FROM ATTENDEE A EXCEPT SELECT V.CITY FROM VENUE V'),
    q('SELECT A1.FAMILY_NAME, A2.FAMILY_NAME FROM ATTENDEE A1 JOIN ATTENDEE A2 ON A1.CITY = A2.CITY AND A1.ATTENDEE_ID < A2.ATTENDEE_ID ORDER BY 1, 2'),
    q('SELECT R1.ATTENDEE_ID, R1.SCREENING_ID, R2.SCREENING_ID FROM RESERVATION R1 JOIN RESERVATION R2 ON R1.ATTENDEE_ID = R2.ATTENDEE_ID AND R1.SCREENING_ID < R2.SCREENING_ID'),
    q("SELECT S.SCREENING_DAY, COUNT(*) AS screenings, SUM(CASE WHEN R.STATUS = 'Waitlist' THEN 1 ELSE 0 END) AS waitlisted FROM SCREENING S LEFT JOIN RESERVATION R ON R.SCREENING_ID = S.SCREENING_ID GROUP BY S.SCREENING_DAY"),
    q("SELECT PASS_TYPE, CITY, COUNT(*) FROM ATTENDEE GROUP BY PASS_TYPE, CITY HAVING COUNT(*) > 1 ORDER BY 1, 2"),
    q('SELECT PASS_TYPE, COUNT(*) FROM ATTENDEE GROUP BY PASS_TYPE ORDER BY COUNT(*) DESC, PASS_TYPE'),
    q('SELECT * FROM ATTENDEE A JOIN VENUE V ON A.CITY = V.CITY'),
    q('SELECT A.*, V.VENUE_NAME FROM ATTENDEE A LEFT JOIN VENUE V ON A.CITY = V.CITY ORDER BY A.ATTENDEE_ID'),
    q('SELECT ATTENDEE.CITY, VENUE.CITY FROM ATTENDEE JOIN VENUE ON ATTENDEE.CITY = VENUE.CITY'),
    refused('SELECT CITY FROM ATTENDEE JOIN VENUE ON ATTENDEE.CITY = VENUE.CITY'),
    q('SELECT V.VENUE_NAME, S.FILM_TITLE, A.FAMILY_NAME FROM VENUE V LEFT JOIN SCREENING S ON S.VENUE_ID = V.VENUE_ID LEFT JOIN RESERVATION R ON R.SCREENING_ID = S.SCREENING_ID LEFT JOIN ATTENDEE A ON A.ATTENDEE_ID = R.ATTENDEE_ID ORDER BY 1, 2, 3'),
    q('SELECT V.VENUE_NAME, S.FILM_TITLE, A.FAMILY_NAME FROM ATTENDEE A RIGHT JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID RIGHT JOIN SCREENING S ON S.SCREENING_ID = R.SCREENING_ID RIGHT JOIN VENUE V ON V.VENUE_ID = S.VENUE_ID ORDER BY 1, 2, 3'),
    q('SELECT A.FAMILY_NAME, S.FILM_TITLE FROM ATTENDEE A FULL OUTER JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID FULL OUTER JOIN SCREENING S ON S.SCREENING_ID = R.SCREENING_ID ORDER BY 1, 2'),
    q("SELECT FILM_TITLE, ROW_NUMBER() OVER (PARTITION BY SCREENING_DAY ORDER BY FILM_TITLE) AS slot FROM SCREENING"),
    q('SELECT ATTENDEE_ID, SCREENING_ID, SEATS, SUM(SEATS) OVER (PARTITION BY ATTENDEE_ID ORDER BY SCREENING_ID) AS running FROM RESERVATION'),
    q('SELECT * FROM RESERVATION WHERE (ATTENDEE_ID, SCREENING_ID) = (301, 701)', 'either'),
    q('SELECT * FROM RESERVATION WHERE ATTENDEE_ID = 301 AND SCREENING_ID = 701'),
    q("SELECT FILM_TITLE FROM SCREENING WHERE FILM_TITLE = 'A;B'"),
    q("SELECT FILM_TITLE FROM SCREENING WHERE FILM_TITLE LIKE '%''%'"),
    q("SELECT FILM_TITLE, REPLACE(FILM_TITLE, ' ', '_') AS slug, SUBSTR(FILM_TITLE, 1, 4) AS head, INSTR(FILM_TITLE, ' ') AS sp, LOWER(FILM_TITLE) AS lo, TRIM('  x  ') AS t FROM SCREENING"),
    q('SELECT SEATS, COUNT(*) FROM RESERVATION GROUP BY SEATS ORDER BY SEATS'),
    q('SELECT STATUS, AVG(SEATS) FROM RESERVATION GROUP BY STATUS HAVING AVG(SEATS) > 1.2'),
    q('SELECT * FROM RESERVATION ORDER BY SEATS DESC, ATTENDEE_ID, SCREENING_ID LIMIT 4 OFFSET 4'),
    q("SELECT A.GIVEN_NAME, COUNT(*) AS c FROM ATTENDEE A JOIN RESERVATION R ON A.ATTENDEE_ID = R.ATTENDEE_ID GROUP BY A.ATTENDEE_ID HAVING c >= 3"),
    q("SELECT FAMILY_NAME FROM ATTENDEE WHERE ATTENDEE_ID IN (SELECT ATTENDEE_ID FROM RESERVATION GROUP BY ATTENDEE_ID HAVING SUM(SEATS) > 3)"),
    q("SELECT FAMILY_NAME FROM ATTENDEE WHERE ATTENDEE_ID IN (SELECT ATTENDEE_ID FROM RESERVATION WHERE SCREENING_ID IN (SELECT SCREENING_ID FROM SCREENING WHERE VENUE_ID IN (SELECT VENUE_ID FROM VENUE WHERE CAPACITY > 100)))"),
    q('SELECT (SELECT COUNT(*) FROM RESERVATION) AS reservations, (SELECT COUNT(*) FROM ATTENDEE) AS attendees'),
    q("SELECT FILM_TITLE FROM SCREENING S WHERE (SELECT SUM(SEATS) FROM RESERVATION R WHERE R.SCREENING_ID = S.SCREENING_ID) > (SELECT AVG(SEATS) * 3 FROM RESERVATION)"),
    q('SELECT * FROM ATTENDEE a, RESERVATION b, SCREENING c, VENUE d WHERE a.ATTENDEE_ID = b.ATTENDEE_ID AND b.SCREENING_ID = c.SCREENING_ID AND c.VENUE_ID = d.VENUE_ID'),
    q('SELECT COUNT(*) FROM RESERVATION a, RESERVATION b, RESERVATION c'),
    { sql: 'SELECT COUNT(*) FROM RESERVATION a, RESERVATION b, RESERVATION c, RESERVATION d', expect: 'either', skipOracle: true },
    either('SELECT * FROM ATTENDEE VENUE JOIN VENUE ATTENDEE ON VENUE.CITY = ATTENDEE.CITY'),
    q('SELECT * FROM ATTENDEE ATTENDEE'),
    q('SELECT RESERVATION.*, SCREENING.FILM_TITLE FROM RESERVATION, SCREENING WHERE RESERVATION.SCREENING_ID = SCREENING.SCREENING_ID AND SEATS > 1'),
  ],
  orchard: [
    q("SELECT P.PLOT_NAME, B.PLOT_NAME AS parent FROM ORCHARD_PLOT P JOIN ORCHARD_PLOT B ON P.PARENT_PLOT_ID = B.PLOT_ID WHERE P.PLOT_ID <> P.PARENT_PLOT_ID ORDER BY 2, 1"),
    q('SELECT B.PLOT_NAME, COUNT(*) - 1 AS children, SUM(P.TREE_COUNT) - B.TREE_COUNT AS child_trees FROM ORCHARD_PLOT B JOIN ORCHARD_PLOT P ON P.PARENT_PLOT_ID = B.PLOT_ID GROUP BY B.PLOT_ID ORDER BY 1'),
    q('SELECT ZONE, SUM(TREE_COUNT), AVG(TREE_COUNT), COUNT(*) FROM ORCHARD_PLOT GROUP BY ZONE HAVING AVG(TREE_COUNT) > 110 ORDER BY 2 DESC'),
    q('SELECT PLOT_NAME FROM ORCHARD_PLOT WHERE PLOT_ID = PARENT_PLOT_ID'),
    q('SELECT PLOT_NAME FROM ORCHARD_PLOT P WHERE TREE_COUNT > (SELECT AVG(TREE_COUNT) FROM ORCHARD_PLOT I WHERE I.ZONE = P.ZONE)'),
    q('SELECT PLOT_NAME, TREE_COUNT, TREE_COUNT - LAG(TREE_COUNT) OVER (PARTITION BY ZONE ORDER BY TREE_COUNT) AS gap FROM ORCHARD_PLOT ORDER BY ZONE, TREE_COUNT'),
    q("SELECT a.PLOT_NAME, b.PLOT_NAME, c.PLOT_NAME FROM ORCHARD_PLOT a JOIN ORCHARD_PLOT b ON a.PARENT_PLOT_ID = b.PLOT_ID JOIN ORCHARD_PLOT c ON b.PARENT_PLOT_ID = c.PLOT_ID WHERE a.PLOT_ID <> b.PLOT_ID ORDER BY 1"),
    q('WITH RECURSIVE tree(id, depth) AS (SELECT PLOT_ID, 0 FROM ORCHARD_PLOT WHERE PLOT_ID = PARENT_PLOT_ID UNION ALL SELECT p.PLOT_ID, t.depth + 1 FROM ORCHARD_PLOT p JOIN tree t ON p.PARENT_PLOT_ID = t.id WHERE p.PLOT_ID <> p.PARENT_PLOT_ID) SELECT * FROM tree ORDER BY depth, id', 'either'),
    q("SELECT PLOT_ID, PLOT_NAME FROM ORCHARD_PLOT WHERE PLOT_ID LIKE 'A%' OR PLOT_ID LIKE 'B%' ORDER BY PLOT_ID"),
    q("SELECT ZONE, MAX(TREE_COUNT) AS most FROM ORCHARD_PLOT WHERE PLOT_ID <> PARENT_PLOT_ID GROUP BY ZONE"),
    q('SELECT * FROM ORCHARD_PLOT P LEFT JOIN ORCHARD_PLOT C ON C.PARENT_PLOT_ID = P.PLOT_ID AND C.PLOT_ID <> P.PLOT_ID WHERE C.PLOT_ID IS NULL'),
  ],
  marine: [
    q("SELECT S.COMMON_NAME, R.REEF_NAME, D.DIVER_NAME, G.COUNT_SEEN FROM SIGHTING G JOIN SPECIES S ON S.SPECIES_CODE = G.SPECIES_CODE JOIN REEF R ON R.REEF_ID = G.REEF_ID JOIN DIVER D ON D.DIVER_ID = G.DIVER_ID WHERE R.DEPTH_M < 20 ORDER BY G.COUNT_SEEN DESC"),
    q('SELECT S.SPECIES_GROUP, SUM(G.COUNT_SEEN) AS seen, COUNT(DISTINCT G.REEF_ID) AS reefs FROM SPECIES S LEFT JOIN SIGHTING G ON G.SPECIES_CODE = S.SPECIES_CODE GROUP BY S.SPECIES_GROUP ORDER BY seen DESC'),
    q('SELECT COMMON_NAME FROM SPECIES WHERE TAG_COLOR IS NULL'),
    q("SELECT COMMON_NAME FROM SPECIES WHERE TAG_COLOR <> 'Blue'"),
    q("SELECT COMMON_NAME FROM SPECIES WHERE TAG_COLOR IS NOT 'Blue'"),
    q("SELECT COMMON_NAME, COALESCE(TAG_COLOR, 'untagged') AS tag FROM SPECIES ORDER BY tag, COMMON_NAME"),
    q('SELECT TAG_COLOR, COUNT(*) FROM SPECIES GROUP BY TAG_COLOR ORDER BY TAG_COLOR'),
    q('SELECT COUNT(TAG_COLOR) AS tagged, COUNT(*) AS all_species, COUNT(DISTINCT TAG_COLOR) AS colours FROM SPECIES'),
    q("SELECT R.REEF_NAME FROM REEF R WHERE R.REEF_ID NOT IN (SELECT REEF_ID FROM SIGHTING WHERE SPECIES_CODE = 'MANT')"),
    q("SELECT R.SECTOR, S.SPECIES_GROUP, SUM(G.COUNT_SEEN) FROM SIGHTING G JOIN REEF R ON R.REEF_ID = G.REEF_ID JOIN SPECIES S ON S.SPECIES_CODE = G.SPECIES_CODE GROUP BY R.SECTOR, S.SPECIES_GROUP ORDER BY 1, 2"),
    q('SELECT D.DIVER_NAME, D.CERT_LEVEL, COUNT(G.SIGHTING_ID) AS dives FROM DIVER D LEFT JOIN SIGHTING G ON G.DIVER_ID = D.DIVER_ID GROUP BY D.DIVER_ID HAVING COUNT(G.SIGHTING_ID) >= 2 ORDER BY dives DESC, D.DIVER_NAME'),
    q('SELECT SPECIES_CODE, COUNT_SEEN, NTILE(3) OVER (ORDER BY COUNT_SEEN) AS bucket FROM SIGHTING'),
    q('SELECT SPECIES_CODE, MAX(COUNT_SEEN) AS best FROM SIGHTING GROUP BY SPECIES_CODE HAVING COUNT(*) > 1 ORDER BY best DESC'),
    q("SELECT G.SIGHTING_ID FROM SIGHTING G WHERE G.COUNT_SEEN > ANY (SELECT COUNT_SEEN FROM SIGHTING WHERE REEF_ID = 'SAN')", 'either'),
    q("SELECT G.SIGHTING_ID FROM SIGHTING G WHERE G.COUNT_SEEN > (SELECT MIN(COUNT_SEEN) FROM SIGHTING WHERE REEF_ID = 'SAN')"),
    q('SELECT DEPTH_M, REEF_NAME FROM REEF WHERE DEPTH_M BETWEEN 9 AND 18 ORDER BY DEPTH_M'),
    q("SELECT REEF_NAME FROM REEF WHERE SECTOR IN ('North', 'East') AND DEPTH_M >= 18 ORDER BY REEF_NAME"),
    q('SELECT SUM(COUNT_SEEN) FROM SIGHTING G JOIN SPECIES S ON S.SPECIES_CODE = G.SPECIES_CODE WHERE S.TAG_COLOR IS NULL'),
    q('SELECT S.COMMON_NAME, R.REEF_NAME FROM SPECIES S CROSS JOIN REEF R WHERE NOT EXISTS (SELECT 1 FROM SIGHTING G WHERE G.SPECIES_CODE = S.SPECIES_CODE AND G.REEF_ID = R.REEF_ID) ORDER BY 1, 2 LIMIT 12'),
  ],
  shop_mysql: [
    q('SELECT * FROM customers'),
    q('SELECT `full_name`, `tier` FROM `customers` WHERE `tier` IN (\'gold\', \'silver\') ORDER BY `full_name`'),
    q("SELECT c.full_name, COUNT(o.order_id) AS orders, IFNULL(SUM(i.qty * i.unit_price), 0) AS spent FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id LEFT JOIN order_items i ON i.order_id = o.order_id GROUP BY c.customer_id ORDER BY spent DESC"),
    q("SELECT p.category, SUM(i.qty) AS units, SUM(i.qty * i.unit_price) AS revenue FROM order_items i JOIN products p ON p.product_id = i.product_id JOIN orders o ON o.order_id = i.order_id WHERE o.status <> 'cancelled' GROUP BY p.category ORDER BY revenue DESC"),
    q('SELECT p.name FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items i WHERE i.product_id = p.product_id)'),
    q('SELECT o.order_id FROM orders o LEFT JOIN order_items i ON i.order_id = o.order_id WHERE i.order_id IS NULL'),
    q('SELECT c.full_name, r.full_name AS referrer FROM customers c LEFT JOIN customers r ON r.customer_id = c.referred_by ORDER BY c.customer_id'),
    q("SELECT c.full_name FROM customers c WHERE c.email IS NULL OR c.email NOT LIKE '%@%'"),
    q("SELECT full_name FROM customers WHERE full_name LIKE '%O\\'Neill%'"),
    q("SELECT full_name FROM customers WHERE full_name = 'Ada O''Neill'"),
    q("SELECT full_name FROM customers WHERE full_name LIKE 'Dagny%'"),
    q("SELECT order_id, DATE_FORMAT(ordered_at, '%Y-%m') AS ym, YEAR(ordered_at) AS y, MONTH(ordered_at) AS m, DAY(ordered_at) AS d FROM orders ORDER BY order_id"),
    q("SELECT order_id, DATEDIFF(NOW(), ordered_at) > 0 AS in_past FROM orders LIMIT 3"),
    q("SELECT order_id FROM orders WHERE ordered_at >= '2025-05-01' AND ordered_at < '2025-06-01'"),
    q("SELECT order_id, TIMESTAMPDIFF(DAY, '2025-01-01', ordered_at) AS days FROM orders ORDER BY days", 'either'),
    q("SELECT status, COUNT(*) FROM orders GROUP BY status WITH ROLLUP", 'either'),
    q('SELECT status, COUNT(*) FROM orders GROUP BY status ORDER BY FIELD(status, \'new\', \'paid\', \'shipped\', \'cancelled\')', 'either'),
    q("SELECT product_id, name, price, IF(discontinued = 1, 'gone', 'live') AS state FROM products"),
    q("SELECT name, price, price * 0.8 AS sale, ROUND(price * 1.2, 2) AS with_tax, TRUNCATE(price, 0) AS whole FROM products ORDER BY price DESC", 'either'),
    either("SELECT name, CONCAT_WS(' / ', sku, category) AS label, CONCAT(name, ' (', sku, ')') AS full FROM products"),
    q("SELECT GROUP_CONCAT(name ORDER BY name SEPARATOR ' | ') FROM products WHERE category = 'kitchen'"),
    q('SELECT category, GROUP_CONCAT(sku) FROM products GROUP BY category'),
    q("SELECT o.order_id, o.status, i.product_id, i.qty FROM orders o INNER JOIN order_items i USING (order_id) WHERE o.customer_id = 1 ORDER BY 1, 3"),
    q('SELECT * FROM orders o STRAIGHT_JOIN customers c ON c.customer_id = o.customer_id', 'either'),
    q("SELECT customer_id, COUNT(*) AS n FROM orders GROUP BY customer_id HAVING n > 1"),
    q('SELECT * FROM orders LIMIT 2, 3'),
    q('SELECT * FROM orders ORDER BY ordered_at DESC LIMIT 3'),
    q("SELECT p.name, p.stock, CASE WHEN p.stock = 0 THEN 'out' WHEN p.stock < 20 THEN 'low' ELSE 'ok' END AS level FROM products p ORDER BY p.stock"),
    q("SELECT i.order_id, i.product_id, i.qty * i.unit_price AS line_total, SUM(i.qty * i.unit_price) OVER (PARTITION BY i.order_id) AS order_total FROM order_items i ORDER BY 1, 2"),
    q('SELECT o.order_id, c.full_name, (SELECT SUM(qty * unit_price) FROM order_items i WHERE i.order_id = o.order_id) AS total FROM orders o JOIN customers c ON c.customer_id = o.customer_id ORDER BY total DESC'),
    q("SELECT c.tier, AVG(t.total) AS avg_order FROM customers c JOIN (SELECT o.customer_id, o.order_id, SUM(i.qty * i.unit_price) AS total FROM orders o JOIN order_items i ON i.order_id = o.order_id GROUP BY o.order_id) t ON t.customer_id = c.customer_id GROUP BY c.tier"),
    q('SELECT customers.full_name FROM customers, orders WHERE customers.customer_id = orders.customer_id AND orders.status = \'new\''),
    q("SELECT DISTINCT c.city FROM customers c", 'refused'),
    q('SELECT product_id FROM products WHERE price BETWEEN 5 AND 15 ORDER BY price'),
    q("SELECT product_id, price DIV 10 AS bucket FROM products"),
    q("SELECT product_id FROM products WHERE sku REGEXP '^MUG'"),
    q("SELECT product_id FROM products WHERE sku RLIKE 'TEA'"),
    q("SELECT product_id FROM products WHERE BINARY sku = 'MUG-001'", 'either'),
    q("SELECT c.full_name FROM customers c WHERE c.customer_id IN (SELECT customer_id FROM orders WHERE status = 'shipped') AND c.customer_id NOT IN (SELECT customer_id FROM orders WHERE status = 'cancelled')"),
  ],
  library_pg: [
    q('SELECT * FROM author'),
    { sql: 'SELECT * FROM public.author', expect: 'ok', lenient: true },
    q('SELECT a.name, COUNT(b.book_id) AS books FROM author a LEFT JOIN book b ON b.author_id = a.author_id GROUP BY a.author_id, a.name ORDER BY books DESC, a.name'),
    q("SELECT b.title, a.name FROM book b LEFT JOIN author a ON a.author_id = b.author_id WHERE a.author_id IS NULL"),
    q('SELECT b.title, m.name, l.loaned_on, l.returned_on FROM loan l JOIN book b ON b.book_id = l.book_id JOIN member m ON m.member_id = l.member_id WHERE l.returned_on IS NULL ORDER BY l.loaned_on'),
    q("SELECT m.name FROM member m WHERE NOT EXISTS (SELECT 1 FROM loan l WHERE l.member_id = m.member_id)"),
    q("SELECT title FROM book WHERE title ILIKE '%invisible%'"),
    q("SELECT title FROM book WHERE title ~ 'night'", 'either'),
    q("SELECT title, published::text AS yr, rating::integer AS r FROM book"),
    q("SELECT title, CAST(rating AS TEXT) AS r, COALESCE(rating, 0) AS r0 FROM book ORDER BY r0 DESC NULLS LAST"),
    q("SELECT title FROM book ORDER BY rating DESC NULLS FIRST"),
    q('SELECT title FROM book ORDER BY rating NULLS LAST LIMIT 3'),
    q("SELECT EXTRACT(YEAR FROM loaned_on) AS y, COUNT(*) FROM loan GROUP BY EXTRACT(YEAR FROM loaned_on)"),
    q("SELECT loan_id, loaned_on + INTERVAL '21 days' AS due, returned_on - loaned_on AS days_out FROM loan"),
    q("SELECT loan_id, DATE_PART('month', loaned_on) AS m FROM loan", 'either'),
    q("SELECT loan_id, AGE(returned_on, loaned_on) FROM loan", 'either'),
    q("SELECT loan_id FROM loan WHERE loaned_on > DATE '2025-05-01'"),
    q("SELECT loan_id FROM loan WHERE loaned_on > '2025-05-01'::date"),
    q("SELECT a.name, STRING_AGG(b.title, '; ' ORDER BY b.title) AS titles FROM author a JOIN book b ON b.author_id = a.author_id GROUP BY a.name", 'either'),
    q("SELECT a.country, COUNT(*) FILTER (WHERE a.born_year < 1930) AS older FROM author a GROUP BY a.country", 'either'),
    q("SELECT DISTINCT ON (author_id) author_id, title FROM book ORDER BY author_id, published DESC", 'either'),
    q('SELECT title FROM book WHERE published IS DISTINCT FROM 1974'),
    q('SELECT title, pages, NTILE(2) OVER (ORDER BY pages) AS half FROM book'),
    q('SELECT title, rating, RANK() OVER (ORDER BY rating DESC NULLS LAST) AS rk FROM book'),
    q("SELECT b.title FROM book b WHERE b.pages > ALL (SELECT pages FROM book WHERE author_id = 4)", 'either'),
    q('SELECT b.title FROM book b WHERE b.pages > (SELECT MAX(pages) FROM book WHERE author_id = 4)'),
    q("SELECT LEFT(title, 5), RIGHT(title, 5), LENGTH(title), UPPER(title), INITCAP(title) FROM book", 'either'),
    q("SELECT SUBSTRING(title FROM 1 FOR 3) AS head, POSITION('a' IN title) AS p, TRIM(BOTH ' ' FROM title) AS t FROM book"),
    q("SELECT title FROM book WHERE title = E'If on a winter\\'s night a traveler'"),
    q("SELECT name FROM author WHERE name = E'Ngũgĩ wa Thiong\\'o'"),
    q('SELECT rowid, raw_title FROM import_staging'),
    q('SELECT * FROM import_staging WHERE rowid = 2'),
    q('SELECT raw_title, COUNT(*) FROM import_staging GROUP BY raw_title'),
    q('SELECT s.raw_title, b.title FROM import_staging s LEFT JOIN book b ON LOWER(b.title) = LOWER(s.raw_title) ORDER BY 1'),
    q('SELECT DISTINCT rowid FROM import_staging ORDER BY 1'),
    q('SELECT COUNT(*) FROM import_staging s1 JOIN import_staging s2 ON s1.rowid = s2.rowid'),
    q("SELECT m.name, (SELECT COUNT(*) FROM loan l WHERE l.member_id = m.member_id AND l.returned_on IS NULL) AS open_loans FROM member m ORDER BY open_loans DESC, m.name"),
    q('SELECT b.book_id FROM book b EXCEPT SELECT l.book_id FROM loan l'),
    q('WITH open AS (SELECT * FROM loan WHERE returned_on IS NULL) SELECT m.name, COUNT(*) FROM open o JOIN member m ON m.member_id = o.member_id GROUP BY m.name'),
    q("SELECT title FROM book WHERE published > 1400 AND pages BETWEEN 150 AND 300 ORDER BY pages"),
    q('SELECT AVG(rating), SUM(pages), MIN(published), MAX(published) FROM book'),
    q('SELECT author_id, AVG(rating) FROM book GROUP BY author_id HAVING AVG(rating) IS NOT NULL ORDER BY 2 DESC'),
  ],
  hr_mssql: [
    q('SELECT * FROM Employee'),
    { sql: 'SELECT * FROM [dbo].[Employee]', expect: 'ok', lenient: true },
    { sql: 'SELECT * FROM dbo.Employee', expect: 'ok', lenient: true },
    q('SELECT TOP 3 [LastName], [Salary] FROM [Employee] ORDER BY [Salary] DESC'),
    q('SELECT TOP 2 PERCENT * FROM Employee', 'either'),
    q('SELECT TOP 3 WITH TIES LastName FROM Employee ORDER BY DeptId', 'either'),
    q('SELECT e.LastName, m.LastName AS Manager FROM Employee e LEFT JOIN Employee m ON m.EmpId = e.ManagerId ORDER BY e.EmpId'),
    q('SELECT d.DeptName, COUNT(e.EmpId) AS headcount, SUM(e.Salary) AS payroll FROM Department d LEFT JOIN Employee e ON e.DeptId = d.DeptId GROUP BY d.DeptId, d.DeptName ORDER BY payroll DESC'),
    q('SELECT e.LastName FROM Employee e WHERE e.DeptId IS NULL'),
    q("SELECT LastName, ISNULL(FirstName, '(none)') AS FirstName, LEN(LastName) AS n FROM Employee"),
    q("SELECT LastName, IIF(IsActive = 1, 'active', 'inactive') AS state FROM Employee"),
    q("SELECT LastName, CONVERT(VARCHAR(10), HiredOn, 120) AS hired, DATEPART(year, HiredOn) AS y, DATEDIFF(day, HiredOn, '2026-01-01') AS days FROM Employee"),
    q("SELECT LastName, YEAR(HiredOn) AS y, DATEADD(day, 30, HiredOn) AS probation FROM Employee", 'either'),
    q("SELECT LastName, GETDATE() > HiredOn AS past FROM Employee LIMIT 2"),
    q("SELECT LastName FROM Employee WHERE HiredOn >= '2021-01-01' AND IsActive = 1 ORDER BY HiredOn"),
    q('SELECT LastName, Salary FROM Employee ORDER BY Salary DESC OFFSET 1 ROWS FETCH NEXT 3 ROWS ONLY'),
    q("SELECT DeptId, AVG(Salary) AS avg_salary FROM Employee GROUP BY DeptId HAVING AVG(Salary) > 100000"),
    q('SELECT p.Name, SUM(a.Pct) AS allocation FROM Project p JOIN Assignment a ON a.ProjectId = p.ProjectId GROUP BY p.ProjectId, p.Name ORDER BY allocation DESC'),
    q("SELECT e.LastName, p.Name, a.Role FROM Assignment a JOIN Employee e ON e.EmpId = a.EmpId JOIN Project p ON p.ProjectId = a.ProjectId WHERE a.Role IS NULL OR a.Role = N'Lead'"),
    q("SELECT LastName FROM Employee WHERE Notes LIKE N'%contractor%'"),
    q('SELECT LastName, Salary, RANK() OVER (PARTITION BY DeptId ORDER BY Salary DESC) AS rk FROM Employee'),
    q('SELECT LastName, Salary, ROW_NUMBER() OVER (ORDER BY Salary DESC) AS rn FROM Employee WHERE Salary IS NOT NULL'),
    q('SELECT e1.LastName, e2.LastName FROM Employee e1 JOIN Employee e2 ON e1.ManagerId = e2.ManagerId AND e1.EmpId < e2.EmpId'),
    q('SELECT e.LastName FROM Employee e WHERE e.EmpId IN (SELECT ManagerId FROM Employee WHERE ManagerId IS NOT NULL)'),
    q('SELECT e.LastName FROM Employee e WHERE e.EmpId NOT IN (SELECT ManagerId FROM Employee)'),
    q('SELECT e.LastName FROM Employee e WHERE e.EmpId NOT IN (SELECT ManagerId FROM Employee WHERE ManagerId IS NOT NULL)'),
    q('SELECT d.DeptName FROM Department d WHERE d.Budget > (SELECT AVG(Budget) FROM Department)'),
    q('SELECT d.DeptName, d.Budget, CAST(d.Budget AS INT) AS whole FROM Department d ORDER BY d.Budget'),
    q("SELECT DeptName FROM Department WHERE DeptName = N'Research & Development'"),
    q("SELECT DeptName FROM Department WHERE DeptName LIKE '%&%'"),
    q("SELECT LastName + ', ' + FirstName AS full FROM Employee", 'either'),
    either("SELECT CONCAT(LastName, ', ', FirstName) AS full FROM Employee"),
    q("SELECT CONCAT(LastName, ', ', FirstName) AS full_name FROM Employee ORDER BY full_name"),
    q('SELECT COUNT(*) FROM Employee WHERE IsActive = 1'),
    q("SELECT COUNT(*) FROM Employee WHERE IsActive = 'true'"),
    q('SELECT e.LastName, COUNT(a.ProjectId) FROM Employee e LEFT JOIN Assignment a ON a.EmpId = e.EmpId GROUP BY e.EmpId, e.LastName HAVING COUNT(a.ProjectId) = 0'),
    q('SELECT p.Name FROM Project p LEFT JOIN Department d ON d.DeptId = p.DeptId WHERE d.DeptId IS NULL'),
    q('SELECT p.Name, d.DeptName FROM Project p FULL OUTER JOIN Department d ON d.DeptId = p.DeptId ORDER BY 1, 2'),
    q("SELECT * FROM Employee WHERE LastName = 'Bergström'"),
    q('SELECT Salary * 12 AS annual, Salary / 12 AS monthly, Salary % 1000 AS rem FROM Employee WHERE Salary IS NOT NULL'),
  ],
  edge_sqlite: [
    q('SELECT * FROM "Mixed_Case"'),
    q('SELECT * FROM mixed_case'),
    q('SELECT * FROM MIXED_CASE WHERE "Value" > 0'),
    q('SELECT "Id", "Value", "Label", "Group" FROM "Mixed_Case" ORDER BY "Group", "Id"'),
    q('SELECT "Group", COUNT(*), SUM("Value") FROM "Mixed_Case" GROUP BY "Group" ORDER BY "Group"'),
    q('SELECT Id, Value FROM Mixed_Case WHERE Value = 0.1 + 0.2'),
    q('SELECT Id FROM Mixed_Case WHERE Value = 0.30000000000000004'),
    q('SELECT Id, Value * 3 AS tripled, ROUND(Value, 2) AS r FROM Mixed_Case ORDER BY Id'),
    q('SELECT Id FROM Mixed_Case WHERE Value < 0 OR Value > 1000000'),
    q("SELECT Id FROM Mixed_Case WHERE Label = ''"),
    q("SELECT Id FROM Mixed_Case WHERE Label = 'O''Brien'"),
    q("SELECT Id FROM Mixed_Case WHERE Label LIKE 'Ñ%'"),
    q("SELECT Id, LENGTH(Label) AS n, UPPER(Label) AS u FROM Mixed_Case WHERE Label LIKE '%🦤%'"),
    q('SELECT Label, COUNT(*) FROM Mixed_Case GROUP BY Label HAVING COUNT(*) > 1'),
    q('SELECT * FROM empty_table'),
    q('SELECT COUNT(*), SUM(id), AVG(id), MAX(name) FROM empty_table'),
    q('SELECT * FROM empty_table e LEFT JOIN single_row s ON s.id = e.id'),
    q('SELECT * FROM single_row s LEFT JOIN empty_table e ON s.id = e.id'),
    q('SELECT * FROM single_row s FULL OUTER JOIN empty_table e ON s.id = e.id'),
    q('SELECT * FROM single_row CROSS JOIN empty_table'),
    q('SELECT name FROM empty_table UNION SELECT note FROM single_row'),
    q('SELECT * FROM single_row WHERE id IN (SELECT id FROM empty_table)'),
    q('SELECT * FROM single_row WHERE id NOT IN (SELECT id FROM empty_table)'),
    q('SELECT * FROM single_row WHERE EXISTS (SELECT 1 FROM empty_table)'),
    q('SELECT id, name, COUNT(*) FROM empty_table GROUP BY id HAVING COUNT(*) > 0'),
    q('SELECT * FROM "order"'),
    q('SELECT order_id, qty FROM "order" WHERE qty > 5'),
    q("SELECT order_id, qty FROM \"order\" WHERE qty > '5'"),
    q('SELECT order_id, CAST(qty AS INTEGER) AS q FROM "order" ORDER BY q DESC'),
    q('SELECT order_id, qty + 0 AS numeric_qty, TYPEOF(qty) FROM "order"'),
    q('SELECT SUM(qty), MAX(qty), MIN(qty) FROM "order"'),
    q('SELECT o.order_id, m.Label FROM "order" o LEFT JOIN "Mixed_Case" m ON m."Id" = o.mixed_id ORDER BY o.order_id'),
    q('SELECT m.Label, COUNT(o.order_id) FROM "Mixed_Case" m LEFT JOIN "order" o ON o.mixed_id = m.Id GROUP BY m.Id ORDER BY 2 DESC, 1'),
    q('SELECT * FROM "order" o JOIN "Mixed_Case" m ON m."Id" = o.mixed_id WHERE m."Group" = \'a\''),
    q('SELECT * FROM keyless'),
    q('SELECT rowid, tag FROM keyless'),
    q('SELECT rowid FROM keyless WHERE rowid = 10'),
    q('SELECT _rowid_, rowid, tag FROM keyless'),
    q('SELECT DISTINCT rowid, tag FROM keyless'),
    q('SELECT tag, COUNT(*), SUM(amount) FROM keyless GROUP BY tag'),
    q('SELECT k1.tag FROM keyless k1 JOIN keyless k2 ON k1.rowid = k2.rowid'),
    q('SELECT * FROM keyless WHERE rowid IS NULL'),
    q('SELECT * FROM keyless ORDER BY rowid DESC'),
    q('SELECT * FROM textkey'),
    q('SELECT "Sku Code", price FROM textkey ORDER BY "Sku Code"'),
    q("SELECT * FROM textkey WHERE \"Sku Code\" = 'SKU 1'"),
    q("SELECT * FROM textkey WHERE \"Sku Code\" = ''"),
    q("SELECT * FROM textkey WHERE LOWER(\"Sku Code\") = 'sku 1'"),
    q("SELECT \"Sku Code\" FROM textkey WHERE \"Sku Code\" LIKE 'sku%'"),
    q('SELECT t.price, t."Sku Code" FROM textkey t WHERE t.price > 0 ORDER BY t.price'),
    q('SELECT * FROM nullable_fk'),
    q('SELECT n.id, m.Label FROM nullable_fk n LEFT JOIN "Mixed_Case" m ON m.Id = n.mixed_id ORDER BY n.id'),
    q('SELECT n.id, m.Label FROM nullable_fk n JOIN "Mixed_Case" m ON m.Id = n.mixed_id'),
    q('SELECT n.id FROM nullable_fk n WHERE n.mixed_id IS NULL'),
    q('SELECT n.id FROM nullable_fk n WHERE n.mixed_id NOT IN (SELECT Id FROM "Mixed_Case" WHERE Id > 2)'),
    q('SELECT m.Id FROM "Mixed_Case" m WHERE m.Id NOT IN (SELECT mixed_id FROM nullable_fk)'),
    q('SELECT SUM(amount), COUNT(amount), COUNT(*) FROM nullable_fk'),
    q('SELECT mixed_id, SUM(amount) FROM nullable_fk GROUP BY mixed_id ORDER BY mixed_id'),
    q('SELECT * FROM nullable_fk n FULL OUTER JOIN "order" o ON o.mixed_id = n.mixed_id ORDER BY n.id, o.order_id'),
    q('SELECT m.Id, n.amount, o.qty FROM "Mixed_Case" m LEFT JOIN nullable_fk n ON n.mixed_id = m.Id LEFT JOIN "order" o ON o.mixed_id = m.Id ORDER BY 1, 2, 3'),
    q('SELECT * FROM "Mixed_Case" WHERE "Group" IS NULL'),
    q('SELECT "Group" FROM "Mixed_Case" GROUP BY "Group"'),
    q('SELECT "Group" AS g FROM "Mixed_Case" ORDER BY g'),
    q('SELECT * FROM "Mixed_Case" WHERE "Group" = \'a\' UNION SELECT * FROM "Mixed_Case" WHERE "Group" = \'b\''),
  ],
};

/* --- mutations, run in order after the read-only battery ---------------- */

const MUTATIONS: Record<string, FuzzQuery[]> = {
  observatory: [
    q("INSERT INTO ASTRONOMER VALUES (7, 'Noor', 'Haddad', 'Tucson')"),
    q("INSERT INTO ASTRONOMER (ASTRONOMER_ID, GIVEN_NAME, FAMILY_NAME, HOME_CITY) VALUES (8, 'Pia', 'Lund', 'Flagstaff'), (9, 'Quin', 'Mora', 'Santa Fe')"),
    refused("INSERT INTO ASTRONOMER VALUES (7, 'Dup', 'Key', 'Tucson')"),
    refused("INSERT INTO ASTRONOMER VALUES (10, NULL, 'Nameless', 'Tucson')"),
    refused("INSERT INTO OBSERVATION VALUES (6000, 999, 'ARC', 101, '2026-06-01', 10)"),
    refused("INSERT INTO OBSERVATION VALUES (6001, 1, 'XXX', 101, '2026-06-01', 10)"),
    q("INSERT INTO OBSERVATION VALUES (6002, 7, 'ARC', 101, '2026-06-02', 12)"),
    q("INSERT INTO TARGET SELECT TARGET_ID + 100, TARGET_NAME || ' II', CONSTELLATION, TARGET_TYPE FROM TARGET WHERE TARGET_TYPE = 'Galaxy'"),
    q("UPDATE ASTRONOMER SET HOME_CITY = 'Tucson' WHERE ASTRONOMER_ID = 8"),
    q("UPDATE ASTRONOMER SET HOME_CITY = 'Tucson' WHERE HOME_CITY = 'Tucson'"),
    q("UPDATE OBSERVATION SET EXPOSURE_MIN = EXPOSURE_MIN + 5 WHERE TELESCOPE_ID = 'ARC'"),
    q("UPDATE OBSERVATION SET EXPOSURE_MIN = (SELECT MAX(EXPOSURE_MIN) FROM OBSERVATION) WHERE OBSERVATION_ID = 5002"),
    q('UPDATE ASTRONOMER SET GIVEN_NAME = UPPER(GIVEN_NAME), FAMILY_NAME = LOWER(FAMILY_NAME) WHERE ASTRONOMER_ID IN (SELECT ASTRONOMER_ID FROM OBSERVATION WHERE EXPOSURE_MIN > 60)'),
    refused('UPDATE ASTRONOMER SET ASTRONOMER_ID = 1 WHERE ASTRONOMER_ID = 2'),
    refused("UPDATE OBSERVATION SET TELESCOPE_ID = 'NOPE' WHERE OBSERVATION_ID = 5001"),
    refused('UPDATE OBSERVATION SET EXPOSURE_MIN = NULL WHERE OBSERVATION_ID = 5001'),
    q('UPDATE OBSERVATION SET EXPOSURE_MIN = 1 WHERE 1 = 0'),
    q('UPDATE ASTRONOMER SET HOME_CITY = HOME_CITY'),
    refused('DELETE FROM ASTRONOMER WHERE ASTRONOMER_ID = 1'),
    q('DELETE FROM ASTRONOMER WHERE ASTRONOMER_ID = 9'),
    q('DELETE FROM OBSERVATION WHERE EXPOSURE_MIN < 20'),
    q("DELETE FROM OBSERVATION WHERE ASTRONOMER_ID IN (SELECT ASTRONOMER_ID FROM ASTRONOMER WHERE HOME_CITY = 'Santa Fe')"),
    q('DELETE FROM TARGET WHERE TARGET_ID > 200'),
    q('DELETE FROM OBSERVATION WHERE 1 = 0'),
    refused('DELETE FROM TELESCOPE'),
    q("REPLACE INTO ASTRONOMER VALUES (7, 'Noor', 'Haddad', 'Albuquerque')"),
    q("INSERT IGNORE INTO ASTRONOMER VALUES (7, 'Ignored', 'Row', 'Nowhere')"),
    q("INSERT INTO ASTRONOMER VALUES (7, 'Noor', 'Haddad-Vale', 'Tucson') ON DUPLICATE KEY UPDATE FAMILY_NAME = 'Haddad-Vale'"),
    q("INSERT INTO ASTRONOMER SET ASTRONOMER_ID = 11, GIVEN_NAME = 'Set', FAMILY_NAME = 'Syntax', HOME_CITY = 'Tucson'"),
    q('DELETE FROM OBSERVATION'),
    q('TRUNCATE TABLE TARGET'),
    q('SELECT COUNT(*) FROM OBSERVATION'),
    q('SELECT * FROM ASTRONOMER ORDER BY ASTRONOMER_ID'),
    q("SELECT A.FAMILY_NAME, COUNT(O.OBSERVATION_ID) FROM ASTRONOMER A LEFT JOIN OBSERVATION O ON O.ASTRONOMER_ID = A.ASTRONOMER_ID GROUP BY A.ASTRONOMER_ID"),
    either('INSERT INTO OBSERVATION VALUES (1, 2, 3)'),
    refused('INSERT INTO NOPE VALUES (1)'),
    refused('UPDATE OBSERVATION SET NOPE = 1'),
    refused("DELETE FROM OBSERVATION WHERE NOPE = 1"),
    refused('INSERT INTO OBSERVATION VALUES (1'),
    refused("UPDATE OBSERVATION SET EXPOSURE_MIN = 1; DELETE FROM OBSERVATION"),
  ],
  festival: [
    q('DELETE FROM ATTENDEE WHERE ATTENDEE_ID = 303'),
    q('DELETE FROM SCREENING WHERE VENUE_ID = 41'),
    refused('DELETE FROM VENUE WHERE VENUE_ID = 42'),
    q("UPDATE RESERVATION SET STATUS = 'Confirmed' WHERE STATUS = 'Waitlist'"),
    q("UPDATE RESERVATION SET SEATS = SEATS * 2 WHERE ATTENDEE_ID = 302"),
    refused("UPDATE RESERVATION SET SCREENING_ID = 701 WHERE ATTENDEE_ID = 302 AND SCREENING_ID = 702"),
    refused("INSERT INTO RESERVATION VALUES (302, 702, 1, 'Confirmed')"),
    q("INSERT INTO RESERVATION VALUES (312, 703, 1, 'Confirmed')"),
    q("INSERT INTO VENUE VALUES (46, 'Pop-up Tent', 'Juniper Bay', 40)"),
    q('UPDATE VENUE SET CAPACITY = CAPACITY + 10 WHERE CITY IN (SELECT CITY FROM ATTENDEE WHERE PASS_TYPE = \'All Access\')'),
    q('SELECT V.VENUE_NAME, COUNT(S.SCREENING_ID) FROM VENUE V LEFT JOIN SCREENING S ON S.VENUE_ID = V.VENUE_ID GROUP BY V.VENUE_ID ORDER BY 1'),
    q('SELECT COUNT(*) FROM RESERVATION'),
    q('DELETE FROM RESERVATION'),
    q('SELECT A.FAMILY_NAME FROM ATTENDEE A LEFT JOIN RESERVATION R ON R.ATTENDEE_ID = A.ATTENDEE_ID WHERE R.ATTENDEE_ID IS NULL'),
  ],
  marine: [
    q("UPDATE SPECIES SET TAG_COLOR = 'Black' WHERE TAG_COLOR IS NULL"),
    q('UPDATE SPECIES SET TAG_COLOR = NULL WHERE SPECIES_GROUP = \'Plant\''),
    q("INSERT INTO SPECIES (SPECIES_CODE, COMMON_NAME, SPECIES_GROUP) VALUES ('NEWX', 'Ghost Pipefish', 'Fish')"),
    refused("INSERT INTO SPECIES VALUES ('TOOLONG', 'x', 'Fish', NULL)"),
    q("INSERT INTO SIGHTING VALUES (9015, 2, 'NEWX', 'BLU', 21)"),
    refused("DELETE FROM SPECIES WHERE SPECIES_CODE = 'NEWX'"),
    q("DELETE FROM SIGHTING WHERE SPECIES_CODE = 'NEWX'"),
    q("DELETE FROM SPECIES WHERE SPECIES_CODE = 'NEWX'"),
    q('SELECT TAG_COLOR, COUNT(*) FROM SPECIES GROUP BY TAG_COLOR'),
  ],
  shop_mysql: [
    q("INSERT INTO customers (customer_id, full_name, email, tier, joined_on, referred_by) VALUES (8, 'Hana Sato', 'hana@example.test', 'silver', '2025-08-01', 1)"),
    q("INSERT INTO `customers` VALUES (9, 'Ivo Petrov', NULL, 'bronze', '2025-08-02', NULL)"),
    refused("INSERT INTO customers VALUES (9, 'Dup', NULL, 'bronze', '2025-08-02', NULL)"),
    refused("INSERT INTO customers VALUES (10, 'Dup Email', 'ada@example.test', 'bronze', '2025-08-02', NULL)"),
    refused("INSERT INTO customers VALUES (11, 'Bad Ref', NULL, 'bronze', '2025-08-02', 999)"),
    q("INSERT IGNORE INTO customers VALUES (9, 'Ignored', NULL, 'bronze', '2025-08-02', NULL)"),
    q("REPLACE INTO customers VALUES (9, 'Ivo Petrov-Replaced', NULL, 'gold', '2025-08-02', NULL)"),
    q("INSERT INTO customers VALUES (9, 'x', NULL, 'bronze', '2025-01-01', NULL) ON DUPLICATE KEY UPDATE tier = 'silver'"),
    q("INSERT INTO orders SET order_id = 11, customer_id = 8, ordered_at = '2025-08-03 10:00:00', status = 'new'"),
    q("INSERT INTO order_items VALUES (11, 101, 1, 14.50), (11, 108, 2, 11.30)"),
    q("UPDATE products SET stock = stock - 1 WHERE product_id IN (SELECT product_id FROM order_items WHERE order_id = 11)"),
    q("UPDATE orders SET status = 'paid' WHERE order_id = 11"),
    q('UPDATE customers SET tier = \'gold\' WHERE customer_id IN (SELECT customer_id FROM orders GROUP BY customer_id HAVING COUNT(*) >= 3)'),
    q('DELETE FROM orders WHERE order_id = 4'),
    q('DELETE FROM customers WHERE customer_id = 1', 'refused'),
    q('DELETE FROM customers WHERE customer_id = 7'),
    q('DELETE FROM customers WHERE customer_id = 2', 'refused'),
    q('SELECT c.full_name, c.referred_by FROM customers c ORDER BY c.customer_id'),
    q('DELETE FROM order_items WHERE order_id IN (SELECT order_id FROM orders WHERE customer_id = 4)'),
    q('DELETE FROM orders WHERE customer_id = 4'),
    q('DELETE FROM customers WHERE customer_id = 4'),
    q('SELECT full_name, referred_by FROM customers WHERE customer_id = 6'),
    q('TRUNCATE TABLE order_items'),
    q('SELECT COUNT(*) FROM order_items'),
  ],
  library_pg: [
    q("INSERT INTO public.book (book_id, title, author_id, published, pages, rating) VALUES (8, 'Kindred', NULL, 1979, 264, 4.6)"),
    refused("INSERT INTO public.book VALUES (9, 'Too Old', NULL, 1200, 10, 1.0)"),
    q('UPDATE book SET rating = 4.0 WHERE rating IS NULL'),
    q('DELETE FROM author WHERE author_id = 3'),
    q('SELECT book_id, title, author_id FROM book WHERE author_id IS NULL ORDER BY book_id'),
    q('DELETE FROM book WHERE book_id = 1'),
    q('SELECT COUNT(*) FROM loan'),
    q('INSERT INTO import_staging VALUES (3, \'kindred\', \'butler\')'),
    q('UPDATE import_staging SET rowid = 99 WHERE rowid IS NULL'),
    q('DELETE FROM import_staging WHERE rowid = 2'),
    q('SELECT * FROM import_staging ORDER BY rowid'),
  ],
  hr_mssql: [
    q("INSERT INTO Employee (EmpId, FirstName, LastName, DeptId, ManagerId, Salary, HiredOn, IsActive, Notes) VALUES (107, N'Noa', N'Levi', 2, 103, 91000.00, '2025-09-01', 1, NULL)"),
    q("INSERT [dbo].[Employee] ([EmpId], [FirstName], [LastName], [DeptId], [ManagerId], [Salary], [HiredOn], [IsActive], [Notes]) VALUES (108, N'Omar', N'Sy', 1, 101, 100000.00, CAST(N'2025-10-01' AS Date), 1, NULL)", 'either'),
    q('UPDATE Employee SET Salary = Salary * 1.05 WHERE DeptId = 1'),
    q('UPDATE [dbo].[Employee] SET [IsActive] = 0 WHERE [EmpId] = 105'),
    refused('DELETE FROM Department WHERE DeptId = 1'),
    q('DELETE FROM Employee WHERE EmpId = 104'),
    q('SELECT COUNT(*) FROM Assignment'),
    refused('DELETE FROM Employee WHERE EmpId = 100'),
    q('UPDATE Employee SET ManagerId = NULL WHERE ManagerId = 100'),
    q('DELETE FROM Assignment WHERE EmpId = 100'),
    q('DELETE FROM Employee WHERE EmpId = 100'),
    q('SELECT e.LastName, m.LastName FROM Employee e LEFT JOIN Employee m ON m.EmpId = e.ManagerId ORDER BY e.EmpId'),
  ],
  edge_sqlite: [
    q('INSERT INTO "Mixed_Case" VALUES (9, 1.5, \'iota\', \'a\')'),
    q('INSERT INTO "Mixed_Case" ("Id", "Label") VALUES (10, \'kappa\')'),
    q("INSERT INTO \"order\" VALUES (6, 9, 'x')"),
    refused("INSERT INTO \"order\" VALUES (7, 999, 'x')"),
    q('INSERT INTO keyless VALUES (12, \'z\', 1)'),
    q('INSERT INTO keyless (tag) VALUES (\'only-tag\')'),
    q("INSERT INTO textkey VALUES ('SKU-3', 30)"),
    refused("INSERT INTO textkey VALUES ('SKU-4', -1)"),
    refused("INSERT INTO textkey VALUES ('SKU 1', 1)"),
    q('UPDATE keyless SET amount = amount + 1 WHERE rowid = 10'),
    q("UPDATE \"order\" SET qty = '12' WHERE order_id = 1"),
    q('UPDATE "Mixed_Case" SET "Group" = \'z\' WHERE "Group" IS NULL'),
    refused('DELETE FROM "Mixed_Case" WHERE "Id" = 1'),
    q('SELECT * FROM nullable_fk ORDER BY id'),
    q('DELETE FROM keyless WHERE rowid IS NULL'),
    q('DELETE FROM keyless'),
    q('SELECT COUNT(*) FROM keyless'),
    q('INSERT INTO empty_table VALUES (1, \'first\')'),
    q('SELECT * FROM empty_table e JOIN single_row s ON s.id = e.id'),
    q('DELETE FROM "order"'),
    q('DELETE FROM nullable_fk'),
    q('DELETE FROM "Mixed_Case"'),
    q('SELECT * FROM "Mixed_Case"'),
  ],
};

export function queriesFor(key: string, schema: TableMeta[], data: Record<string, TableData>): FuzzQuery[] {
  const generic = genericQueries(schema, data);
  return [...generic, ...(HAND[key] ?? []), ...(MUTATIONS[key] ?? []), ...generic.slice(0, Math.min(40, generic.length))];
}
