import type { Case } from '../testDialects';
import { PROBES as ROUND1 } from './exports';

const defOf = (label: string) => ROUND1.find((p) => p.label === label)!.def;

const pg: Case[] = [
  { sql: 'SELECT name, price, LAG(price) OVER (ORDER BY id) AS prev FROM product ORDER BY id', rows: [['Hammer', 12.5, null], ['Saw', 24, 12.5], ['Trowel', 7.25, 24], ['Hose', 30, 7.25]], ordered: true },
  { sql: 'SELECT name FROM product ORDER BY CASE WHEN in_stock THEN 0 ELSE 1 END, price DESC', rows: [['Hose'], ['Hammer'], ['Trowel'], ['Saw']], ordered: true },
  { sql: "SELECT COALESCE(tags, '(none)') AS t, COUNT(*) AS n FROM product GROUP BY COALESCE(tags, '(none)') ORDER BY t", rows: [['(none)', 1], ['{rubber}', 1], ['{steel,hand}', 1], ['{steel}', 1]], ordered: true },
  { sql: 'SELECT category_id, COUNT(*) AS n, SUM(price) AS total FROM product GROUP BY category_id HAVING total > 30 ORDER BY category_id', rows: [[1, 2, 36.5], [2, 2, 37.25]], ordered: true },
  { sql: 'WITH a AS (SELECT * FROM product WHERE in_stock), b AS (SELECT category_id, MAX(price) AS mx FROM a GROUP BY category_id) SELECT c.name, b.mx FROM b JOIN category c ON c.id = b.category_id ORDER BY c.name', rows: [['Garden', 30], ['Tools', 12.5]], ordered: true },
  { sql: "SELECT name FROM product p WHERE EXISTS (SELECT 1 FROM category c WHERE c.id = p.category_id AND c.name = 'Garden') ORDER BY name", rows: [['Hose'], ['Trowel']], ordered: true },
  { sql: 'SELECT name FROM product WHERE price > 20 UNION SELECT name FROM category WHERE id = 3 ORDER BY 1 LIMIT 2', rows: [['Empty'], ['Hose']], ordered: true },
  { sql: "SELECT REPLACE(UPPER(name), 'A', '4') AS r, LENGTH(name) AS n, TRIM('  x  ') AS t, INITCAP('hello world') AS i FROM product WHERE id = 1", rows: [['H4MMER', 6, 'x', 'Hello World']] },
  { sql: 'SELECT ROUND(price / 3, 2) AS r, CEIL(price / 3) AS c, FLOOR(price / 3) AS f, ABS(-price) AS a, MOD(CAST(price AS INTEGER), 5) AS m, POWER(2, 3) AS p FROM product WHERE id = 2', rows: [[8, 8, 8, 24, 4, 8]] },
  { sql: 'SELECT name FROM product WHERE id NOT IN (SELECT category_id FROM product WHERE tags IS NULL)', rows: [['Hammer'], ['Trowel'], ['Hose']] },
  { sql: 'SELECT p1.name, p2.name FROM product p1 JOIN product p2 ON p1.category_id = p2.category_id AND p1.id < p2.id ORDER BY 1', rows: [['Hammer', 'Saw'], ['Trowel', 'Hose']], ordered: true },
  { sql: 'SELECT DISTINCT category_id FROM product ORDER BY category_id DESC LIMIT 1 OFFSET 1', rows: [[1]] },
  { sql: 'SELECT name, (SELECT name FROM category WHERE id = p.category_id) AS cat FROM product p WHERE price = (SELECT MIN(price) FROM product)', rows: [['Trowel', 'Garden']] },
  { sql: 'SELECT category_id, in_stock, COUNT(*) AS n FROM product GROUP BY category_id, in_stock ORDER BY category_id, in_stock', rows: [[1, 0, 1], [1, 1, 1], [2, 1, 2]], ordered: true },
  { sql: 'SELECT SUM(CASE WHEN in_stock THEN 1 ELSE 0 END) AS stocked, COUNT(CASE WHEN NOT in_stock THEN 1 END) AS out FROM product', rows: [[3, 1]] },
  { sql: "SELECT name, DATE_TRUNC('week', added_on) AS wk FROM product WHERE id = 1", rows: [['Hammer', '2025-01-13 00:00:00']] },
  { sql: "SELECT name, TO_CHAR(added_on, 'Day') AS d FROM product WHERE id = 2", rows: [['Saw', 'Friday']] },
  { sql: "SELECT name, added_on + INTERVAL '3 months' AS later FROM product WHERE id = 4", rows: [['Hose', '2026-03-31']] },
  { sql: "SELECT name FROM product WHERE name ILIKE 's%' OR name ILIKE '%L' ORDER BY 1", rows: [['Saw'], ['Trowel']], ordered: true },
  { sql: 'SELECT name, price / NULLIF(0, 0) AS z FROM product WHERE id = 1', rows: [['Hammer', null]] },
  { sql: 'SELECT name, price::numeric * 1.1 AS up FROM product WHERE id = 3', rows: [['Trowel', 7.975]] },
  { sql: "SELECT name || ' (' || category_id || ')' AS label FROM product WHERE id = 4", rows: [['Hose (2)']] },
  { sql: 'SELECT EXTRACT(DOW FROM added_on) AS dow, COUNT(*) AS n FROM product GROUP BY 1 ORDER BY 1', rows: [[3, 2], [5, 1], [6, 1]], ordered: true },
  { sql: 'UPDATE product SET price = price - 5 WHERE id IN (SELECT id FROM product WHERE price > 20)', ok: true },
  { sql: 'SELECT id, price FROM product WHERE id IN (2, 4) ORDER BY id', rows: [[2, 19], [4, 25]], ordered: true },
  { sql: "INSERT INTO product (category_id, name, price, in_stock) SELECT id, name || ' kit', 9.99, FALSE FROM category WHERE id <> 3", ok: true },
  { sql: 'SELECT COUNT(*) FROM product WHERE in_stock = FALSE', rows: [[3]] },
  { sql: "DELETE FROM product WHERE name LIKE '% kit'", ok: true },
  { sql: 'SELECT COUNT(*) FROM product', rows: [[4]] },
  { sql: 'UPDATE category SET name = LOWER(name)', ok: true },
  { sql: 'SELECT name FROM category ORDER BY id', rows: [['tools'], ['garden'], ['empty']], ordered: true },
  { sql: 'DELETE FROM category WHERE id NOT IN (SELECT DISTINCT category_id FROM product)', ok: true },
  { sql: 'SELECT COUNT(*) FROM category', rows: [[2]] },
  { sql: "INSERT INTO category VALUES (3, 'Empty')", ok: true },
  { sql: 'SELECT MAX(id) FROM category', rows: [[3]] },
];

const mysql: Case[] = [
  { sql: 'SELECT c.code, c.credits, COUNT(e.id) AS n FROM courses c LEFT JOIN enrollments e ON e.course_code = c.code GROUP BY c.code, c.credits ORDER BY n DESC, c.code', rows: [['CS101', 4, 3], ['HI110', 3, 1], ['MA201', 3, 1]], ordered: true },
  { sql: 'SELECT name FROM students ORDER BY LENGTH(name) DESC, name LIMIT 2', rows: [['Cy "The Cat" Lee'], ["Ben O'Hara"]], ordered: true },
  { sql: "SELECT s.name, COALESCE(s.email, CONCAT(LOWER(SUBSTRING_INDEX(s.name, ' ', 1)), '@none')) AS contact FROM students s WHERE s.id = 2", rows: [["Ben O'Hara", 'ben@none']] },
  { sql: "SELECT name, IF(gpa IS NULL, 'n/a', IF(gpa >= 3.5, 'high', 'mid')) AS band FROM students ORDER BY id", rows: [['Ana Díaz', 'high'], ["Ben O'Hara", 'mid'], ['Cy "The Cat" Lee', 'n/a'], ['Dee Wu', 'mid']], ordered: true },
  { sql: "SELECT DATE_FORMAT(enrolled, '%W, %D %M %Y') AS d FROM students WHERE id = 3", rows: [['Wednesday, 15th January 2025']] },
  { sql: 'SELECT name, DATEDIFF(CURDATE(), enrolled) > 365 AS old FROM students WHERE id = 1', rows: [['Ana Díaz', 1]] },
  { sql: 'SELECT name FROM students WHERE id IN (SELECT student_id FROM enrollments WHERE course_code IN (SELECT code FROM courses WHERE credits = 3)) ORDER BY name', rows: [['Ana Díaz'], ['Dee Wu']], ordered: true },
  { sql: "SELECT CONCAT_WS(' | ', code, title, credits) AS line FROM courses ORDER BY code", rows: [['CS101 | Intro to CS | 4'], ['HI110 | World History | 3'], ['MA201 | Linear Algebra | 3']], ordered: true },
  { sql: "SELECT name FROM students WHERE email REGEXP '^[a-c]' ORDER BY 1", rows: [['Ana Díaz'], ['Cy "The Cat" Lee']], ordered: true },
  { sql: 'SELECT YEAR(enrolled) AS y, COUNT(*) AS n FROM students GROUP BY YEAR(enrolled) ORDER BY y', rows: [[2024, 2], [2025, 2]], ordered: true },
  { sql: "SELECT ROUND(AVG(gpa), 1) AS a FROM students WHERE enrolled BETWEEN '2024-01-01' AND '2024-12-31'", rows: [[3.4]] },
  { sql: "SELECT s.name FROM students s LEFT JOIN enrollments e ON e.student_id = s.id AND e.term = 'spring' WHERE e.id IS NULL ORDER BY s.id", rows: [['Ana Díaz'], ["Ben O'Hara"], ['Cy "The Cat" Lee']], ordered: true },
  { sql: 'SELECT student_id, GROUP_CONCAT(course_code ORDER BY course_code) AS codes FROM enrollments WHERE student_id = 1 GROUP BY student_id', rows: [[1, 'CS101,MA201']] },
  { sql: 'SELECT code FROM courses WHERE code NOT IN (SELECT course_code FROM enrollments WHERE grade IS NOT NULL)', rows: [['HI110']] },
  { sql: "SELECT term, AVG(CASE grade WHEN 'A' THEN 4 WHEN 'A-' THEN 3.7 WHEN 'B+' THEN 3.3 WHEN 'C' THEN 2 END) AS gpa FROM enrollments GROUP BY term ORDER BY term", rows: [['fall', 3.1], ['spring', 3.7]], ordered: true },
  { sql: "UPDATE enrollments SET grade = 'B' WHERE grade IS NULL", ok: true },
  { sql: 'SELECT grade FROM enrollments WHERE id = 4', rows: [['B']] },
  { sql: "INSERT INTO students (name, email, gpa, enrolled) VALUES ('Eli Ng', NULL, 3.0, '2025-09-01'), ('Fay Oz', NULL, NULL, '2025-09-01')", ok: true },
  { sql: 'SELECT COUNT(*) FROM students', rows: [[6]] },
  { sql: 'DELETE FROM students WHERE gpa IS NULL AND active = 0', ok: true },
  { sql: 'SELECT COUNT(*) FROM students', rows: [[5]] },
  { sql: 'UPDATE courses SET credits = credits + 1 WHERE code IN (SELECT course_code FROM enrollments GROUP BY course_code HAVING COUNT(*) >= 2)', ok: true },
  { sql: "SELECT credits FROM courses WHERE code = 'CS101'", rows: [[5]] },
  { sql: "REPLACE INTO students (id, name, enrolled) VALUES (1, 'Ana D.', '2024-09-01')", ok: true },
  { sql: 'SELECT COUNT(*) FROM enrollments WHERE student_id = 1', rows: [[0]] },
  { sql: 'SELECT name, email, gpa, active FROM students WHERE id = 1', rows: [['Ana D.', null, null, 1]] },
];

const mssql: Case[] = [
  { sql: 'SELECT TOP 1 p.FullName, SUM(v.Cost) AS Total FROM Patient p JOIN Visit v ON v.PatientId = p.PatientId GROUP BY p.PatientId, p.FullName ORDER BY Total DESC', rows: [['Ola Nordmann', 120.5]] },
  { sql: 'SELECT FullName FROM Patient ORDER BY FullName OFFSET 0 ROWS FETCH FIRST 2 ROWS ONLY', rows: [['Kari Hansen'], ['Ola Nordmann']], ordered: true },
  { sql: "SELECT VisitId, DATEDIFF(day, VisitedAt, '2025-12-31') AS DaysAgo, DATEADD(week, 2, CAST(VisitedAt AS DATE)) AS FollowUp FROM Visit ORDER BY VisitId", rows: [[1, 296, '2025-03-24'], [2, 199, '2025-06-29'], [3, 183, '2025-07-15']], ordered: true },
  { sql: "SELECT FORMAT(Balance, 'N2') AS b FROM Patient WHERE PatientId = 1", rows: [['120.50']] },
  { sql: "SELECT FullName, CASE WHEN BirthDate IS NULL THEN 'unknown' WHEN DATEDIFF(year, BirthDate, '2026-01-01') >= 40 THEN 'senior' ELSE 'junior' END AS Grp FROM Patient ORDER BY PatientId", rows: [['Ola Nordmann', 'senior'], ['Kari Hansen', 'junior'], ['Per Olsen', 'unknown']], ordered: true },
  { sql: 'SELECT p.FullName, v.Reason FROM Patient p CROSS JOIN Visit v WHERE p.PatientId <> v.PatientId AND v.Reason IS NOT NULL ORDER BY 1, 2', rows: [['Kari Hansen', 'Checkup'], ['Kari Hansen', 'Follow-up'], ['Per Olsen', 'Checkup'], ['Per Olsen', 'Follow-up']], ordered: true },
  { sql: "SELECT CHARINDEX('a', LOWER(FullName)) AS p, REPLACE(FullName, ' ', '_') AS r, LEN('  pad  ') AS l FROM Patient WHERE PatientId = 2", rows: [[2, 'Kari_Hansen', 5]] },
  { sql: 'SELECT VisitId, Cost, AVG(Cost) OVER () AS AvgCost, Cost - AVG(Cost) OVER () AS Diff FROM Visit ORDER BY VisitId', rows: [[1, 80, 55.16666667, 24.83333333], [2, 40.5, 55.16666667, -14.66666667], [3, 45, 55.16666667, -10.16666667]], ordered: true },
  { sql: 'SELECT ISNULL(SUM(Cost), 0) AS Total FROM Visit WHERE PatientId = 2', rows: [[0]] },
  { sql: "UPDATE Visit SET Reason = N'Unknown' WHERE Reason IS NULL", ok: true },
  { sql: "INSERT INTO Visit (PatientId, VisitedAt, Reason, Cost) VALUES (2, '2025-08-01 09:00:00', N'Intake', 60.00)", ok: true },
  { sql: 'SELECT VisitId FROM Visit WHERE PatientId = 2', rows: [[4]] },
  { sql: 'DELETE FROM Patient WHERE PatientId = 2', ok: true },
  { sql: 'SELECT COUNT(*) FROM Visit', rows: [[3]] },
  { sql: 'UPDATE Patient SET Balance = Balance * 2 WHERE PatientId NOT IN (SELECT PatientId FROM Visit)', ok: true },
  { sql: 'SELECT SUM(Balance) FROM Patient', rows: [[165.5]] },
];

const oracle: Case[] = [
  { sql: "SELECT ENAME, NVL(TO_CHAR(COMM), 'none') AS C FROM EMP WHERE DEPTNO = 30 ORDER BY ENAME", rows: [['ALLEN', '300'], ['BLAKE', 'none'], ['WARD', '500']], ordered: true },
  { sql: "SELECT ENAME, DECODE(JOB, 'CLERK', 'C', 'MANAGER', 'M', 'X') AS J FROM EMP WHERE DEPTNO = 10 ORDER BY ENAME", rows: [['CLARK', 'M'], ['KING', 'X'], ['MILLER', 'C']], ordered: true },
  { sql: "SELECT ENAME, MONTHS_BETWEEN(TO_DATE('1982-01-23','YYYY-MM-DD'), HIREDATE) AS M FROM EMP WHERE EMPNO IN (7934, 7369) ORDER BY EMPNO", rows: [['SMITH', 13.19354839], ['MILLER', 0]], ordered: true },
  { sql: 'SELECT ENAME, ADD_MONTHS(HIREDATE, -1) AS PREV FROM EMP WHERE EMPNO = 7499', rows: [['ALLEN', '1981-01-20']] },
  { sql: 'SELECT * FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC) T WHERE ROWNUM <= 2', rows: [['KING', 5000], ['FORD', 3000]] },
  { sql: "SELECT ENAME FROM EMP WHERE DEPTNO = 20 MINUS SELECT ENAME FROM EMP WHERE JOB = 'CLERK'", rows: [['JONES'], ['FORD']] },
  { sql: "SELECT JOB, LISTAGG(ENAME, '/') WITHIN GROUP (ORDER BY ENAME) AS L FROM EMP WHERE JOB = 'MANAGER' GROUP BY JOB", rows: [['MANAGER', 'JONES/BLAKE/CLARK']] },
  { sql: 'SELECT E.ENAME FROM EMP E WHERE E.SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO = E.DEPTNO) ORDER BY E.ENAME', rows: [['BLAKE'], ['FORD'], ['JONES'], ['KING']], ordered: true },
  { sql: "SELECT SUBSTR(ENAME, -3) AS S, INSTR(ENAME, 'L') AS I FROM EMP WHERE EMPNO = 7499", rows: [['LEN', 2]] },
  { sql: 'SELECT ROUND(SAL / 1000, 1) AS K, TRUNC(SAL / 1000) AS T, CEIL(SAL / 1000) AS C FROM EMP WHERE EMPNO = 7566', rows: [[3, 2, 3]] },
  { sql: 'SELECT ENAME, SYSDATE - HIREDATE > 365 AS LONGAGO FROM EMP WHERE EMPNO = 7369', rows: [['SMITH', 1]] },
  { sql: "SELECT ENAME || ': ' || JOB AS LINE FROM EMP WHERE SAL BETWEEN 1250 AND 1600 ORDER BY SAL", rows: [['WARD: SALESMAN'], ['MILLER: CLERK'], ['ALLEN: SALESMAN']], ordered: true },
  { sql: 'SELECT ENAME FROM EMP ORDER BY HIREDATE FETCH FIRST 3 ROWS ONLY', rows: [['SMITH'], ['ALLEN'], ['WARD']], ordered: true },
  { sql: 'SELECT DEPTNO, SUM(SAL) AS TOTAL, RANK() OVER (ORDER BY SUM(SAL) DESC) AS RK FROM EMP GROUP BY DEPTNO ORDER BY RK', rows: [[10, 8750, 1], [20, 6775, 2], [30, 5700, 3]], ordered: true },
  { sql: 'SELECT D.DNAME, (SELECT COUNT(*) FROM EMP E WHERE E.DEPTNO = D.DEPTNO AND E.COMM IS NOT NULL) AS WITH_COMM FROM DEPT D ORDER BY D.DEPTNO', rows: [['ACCOUNTING', 0], ['RESEARCH', 0], ['SALES', 2], ['OPERATIONS', 0]], ordered: true },
  { sql: "SELECT E.ENAME, M.ENAME AS MGR_NAME FROM EMP E JOIN EMP M ON M.EMPNO = E.MGR WHERE M.JOB = 'MANAGER' ORDER BY E.ENAME", rows: [['ALLEN', 'BLAKE'], ['FORD', 'JONES'], ['MILLER', 'CLARK'], ['WARD', 'BLAKE']], ordered: true },
  { sql: "UPDATE EMP SET COMM = 0 WHERE COMM IS NULL AND JOB = 'SALESMAN'", ok: true },
  { sql: "INSERT INTO EMP (EMPNO, ENAME, JOB, HIREDATE, SAL, DEPTNO) VALUES (7999, 'NEWBIE', 'CLERK', SYSDATE, 900, 40)", ok: true },
  { sql: 'SELECT ENAME, DEPTNO, LENGTH(HIREDATE) >= 10 AS HAS_DATE FROM EMP WHERE EMPNO = 7999', rows: [['NEWBIE', 40, 1]] },
  { sql: 'DELETE FROM EMP WHERE EMPNO = 7999', ok: true },
  { sql: 'DELETE FROM DEPT WHERE DEPTNO = 40', ok: true },
  { sql: 'SELECT COUNT(*) FROM DEPT', rows: [[3]] },
  { sql: 'UPDATE DEPT SET LOC = INITCAP(LOC)', ok: true },
  { sql: 'SELECT LOC FROM DEPT ORDER BY DEPTNO', rows: [['New York'], ['Dallas'], ['Chicago']], ordered: true },
];

export const PROBES = [
  { label: 'queries shop_pg', def: defOf('shop_pg'), cases: pg },
  { label: 'queries school_pma', def: defOf('school_pma'), cases: mysql },
  { label: 'queries clinic_mssql', def: defOf('clinic_mssql'), cases: mssql },
  { label: 'queries scott_ora', def: defOf('scott_ora'), cases: oracle },
];
